# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ArchivalLocationConnectJob(Model):
    """ArchivalLocationConnectJob.

    :param data_location_id:
    :type data_location_id: str
    :param name:
    :type name: str
    :param job_id:
    :type job_id: str
    :param location_type:
    :type location_type: str
    :param host:
    :type host: str
    :param bucket: Bucket name cannot contain whitespace or _\\\\/*?%.:|<> For
     AWS, bucket name also cannot contain capital letters or underscore
    :type bucket: str
    """

    _validation = {
        'data_location_id': {'required': True},
        'name': {'required': True},
        'job_id': {'required': True},
        'location_type': {'required': True},
    }

    _attribute_map = {
        'data_location_id': {'key': 'dataLocationId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'job_id': {'key': 'jobId', 'type': 'str'},
        'location_type': {'key': 'locationType', 'type': 'str'},
        'host': {'key': 'host', 'type': 'str'},
        'bucket': {'key': 'bucket', 'type': 'str'},
    }

    def __init__(self, data_location_id, name, job_id, location_type, host=None, bucket=None):
        self.data_location_id = data_location_id
        self.name = name
        self.job_id = job_id
        self.location_type = location_type
        self.host = host
        self.bucket = bucket
