# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BulkDeleteUnmanagedObjectSnapshots(Model):
    """BulkDeleteUnmanagedObjectSnapshots.

    :param object_definitions:
    :type object_definitions: list of :class:`UnmanagedObjectDefinition
     <rubriklib_int.models.UnmanagedObjectDefinition>`
    """

    _validation = {
        'object_definitions': {'required': True},
    }

    _attribute_map = {
        'object_definitions': {'key': 'objectDefinitions', 'type': '[UnmanagedObjectDefinition]'},
    }

    def __init__(self, object_definitions):
        self.object_definitions = object_definitions
