# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CloudInstantiationSpec(Model):
    """CloudInstantiationSpec.

    :param image_retention_in_seconds: Specifies the number of seconds to
     retain an image file that is generated for a snappable. Setting this to -1
     disables cloud instantiation for the snappable.
    :type image_retention_in_seconds: long
    """

    _validation = {
        'image_retention_in_seconds': {'required': True},
    }

    _attribute_map = {
        'image_retention_in_seconds': {'key': 'imageRetentionInSeconds', 'type': 'long'},
    }

    def __init__(self, image_retention_in_seconds):
        self.image_retention_in_seconds = image_retention_in_seconds
