# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .cloud_image_summary_links import CloudImageSummaryLinks


class CloudImageDetailLinks(CloudImageSummaryLinks):
    """CloudImageDetailLinks.

    :param snappable:
    :type snappable: :class:`Link <rubriklib_int.models.Link>`
    :param snapshot:
    :type snapshot: :class:`Link <rubriklib_int.models.Link>`
    :param location:
    :type location: :class:`Link <rubriklib_int.models.Link>`
    :param instance_ids:
    :type instance_ids: list of :class:`Link <rubriklib_int.models.Link>`
    """

    _attribute_map = {
        'snappable': {'key': 'snappable', 'type': 'Link'},
        'snapshot': {'key': 'snapshot', 'type': 'Link'},
        'location': {'key': 'location', 'type': 'Link'},
        'instance_ids': {'key': 'instanceIds', 'type': '[Link]'},
    }

    def __init__(self, snappable=None, snapshot=None, location=None, instance_ids=None):
        super(CloudImageDetailLinks, self).__init__(snappable=snappable, snapshot=snapshot, location=location)
        self.instance_ids = instance_ids
