# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CloudInstanceSummary(Model):
    """CloudInstanceSummary.

    :param id: The ID of the cloud instance
    :type id: str
    :param snappable_id: The ID of the source snappable. Will be empty if the
     snappable is not available.
    :type snappable_id: str
    :param snappable_name: The name of the source snappable. Will be empty if
     the snappable is not available.
    :type snappable_name: str
    :param location_id: The data location the cloud instance is on
    :type location_id: str
    :param location_name: The name of the location the cloud instance is on
    :type location_name: str
    :param image_id: The image the cloud instance was generated from
    :type image_id: str
    :param creation_date: The date the instance was created
    :type creation_date: datetime
    :param termination_date: The date the instance is scheduled to terminate
    :type termination_date: datetime
    :param instance_class: The type of instance for relative to Rubrik.
     Possible values include: 'UserDeployedRubrikOnCloudInstance',
     'TransientRubrikOnCloudInstance', 'UserInstantiatedInstance'
    :type instance_class: str or :class:`enum <rubriklib_int.models.enum>`
    :param public_ip_address: The public IP address of the instance
    :type public_ip_address: str
    :param private_ip_address: The private IP address of the instance
    :type private_ip_address: str
    :param power_status: The power status. Possible values include: 'PENDING',
     'RUNNING', 'SHUTTING_DOWN', 'TERMINATED', 'STOPPING', 'STOPPED'
    :type power_status: str or :class:`enum <rubriklib_int.models.enum>`
    :param owner_id: ID of the user who requested the instance.
    :type owner_id: str
    :param owner_name: Displayable name of the user who requested the
     instance.
    :type owner_name: str
    :param links:
    :type links: :class:`CloudInstanceLinks
     <rubriklib_int.models.CloudInstanceLinks>`
    """

    _validation = {
        'id': {'required': True},
        'location_id': {'required': True},
        'location_name': {'required': True},
        'image_id': {'required': True},
        'creation_date': {'required': True},
        'instance_class': {'required': True},
        'owner_id': {'required': True},
        'owner_name': {'required': True},
        'links': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'snappable_id': {'key': 'snappableId', 'type': 'str'},
        'snappable_name': {'key': 'snappableName', 'type': 'str'},
        'location_id': {'key': 'locationId', 'type': 'str'},
        'location_name': {'key': 'locationName', 'type': 'str'},
        'image_id': {'key': 'imageId', 'type': 'str'},
        'creation_date': {'key': 'creationDate', 'type': 'iso-8601'},
        'termination_date': {'key': 'terminationDate', 'type': 'iso-8601'},
        'instance_class': {'key': 'instanceClass', 'type': 'str'},
        'public_ip_address': {'key': 'publicIpAddress', 'type': 'str'},
        'private_ip_address': {'key': 'privateIpAddress', 'type': 'str'},
        'power_status': {'key': 'powerStatus', 'type': 'str'},
        'owner_id': {'key': 'ownerId', 'type': 'str'},
        'owner_name': {'key': 'ownerName', 'type': 'str'},
        'links': {'key': 'links', 'type': 'CloudInstanceLinks'},
    }

    def __init__(self, id, location_id, location_name, image_id, creation_date, instance_class, owner_id, owner_name, links, snappable_id=None, snappable_name=None, termination_date=None, public_ip_address=None, private_ip_address=None, power_status=None):
        self.id = id
        self.snappable_id = snappable_id
        self.snappable_name = snappable_name
        self.location_id = location_id
        self.location_name = location_name
        self.image_id = image_id
        self.creation_date = creation_date
        self.termination_date = termination_date
        self.instance_class = instance_class
        self.public_ip_address = public_ip_address
        self.private_ip_address = private_ip_address
        self.power_status = power_status
        self.owner_id = owner_id
        self.owner_name = owner_name
        self.links = links
