# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClusterIpConfig(Model):
    """ClusterIpConfig.

    :param netmask:
    :type netmask: str
    :param gateway:
    :type gateway: str
    """

    _validation = {
        'netmask': {'required': True},
        'gateway': {'required': True},
    }

    _attribute_map = {
        'netmask': {'key': 'netmask', 'type': 'str'},
        'gateway': {'key': 'gateway', 'type': 'str'},
    }

    def __init__(self, netmask, gateway):
        self.netmask = netmask
        self.gateway = gateway
