# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClusterTimezone(Model):
    """ClusterTimezone.

    :param timezone: Cluster Timezone. Possible values include:
     'America/Anchorage', 'America/Araguaina', 'America/Barbados',
     'America/Chicago', 'America/Denver', 'America/Los_Angeles',
     'America/Mexico_City', 'America/New_York', 'America/Noronha',
     'America/Phoenix', 'America/Toronto', 'America/Vancouver', 'Asia/Bangkok',
     'Asia/Dhaka', 'Asia/Dubai', 'Asia/Hong_Kong', 'Asia/Karachi',
     'Asia/Magadan', 'Asia/Singapore', 'Asia/Tokyo', 'Atlantic/Cape_Verde',
     'Australia/Perth', 'Australia/Sydney', 'Europe/Amsterdam',
     'Europe/Athens', 'Europe/London', 'Europe/Moscow', 'Pacific/Auckland',
     'Pacific/Honolulu', 'Pacific/Midway', 'UTC'
    :type timezone: str or :class:`enum <rubriklib_int.models.enum>`
    """

    _validation = {
        'timezone': {'required': True},
    }

    _attribute_map = {
        'timezone': {'key': 'timezone', 'type': 'str'},
    }

    def __init__(self, timezone):
        self.timezone = timezone
