# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClusterConfig(Model):
    """ClusterConfig.

    :param name:
    :type name: str
    :param ntp_servers:
    :type ntp_servers: list of str
    :param dns_nameservers:
    :type dns_nameservers: list of str
    :param dns_search_domains:
    :type dns_search_domains: list of str
    :param node_configs:
    :type node_configs: dict
    :param admin_user_info:
    :type admin_user_info: :class:`AdminUserConfig
     <rubriklib_int.models.AdminUserConfig>`
    :param enable_software_encryption_at_rest:
    :type enable_software_encryption_at_rest: bool
    """

    _validation = {
        'name': {'required': True},
        'ntp_servers': {'required': True},
        'dns_nameservers': {'required': True},
        'node_configs': {'required': True},
        'admin_user_info': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'ntp_servers': {'key': 'ntpServers', 'type': '[str]'},
        'dns_nameservers': {'key': 'dnsNameservers', 'type': '[str]'},
        'dns_search_domains': {'key': 'dnsSearchDomains', 'type': '[str]'},
        'node_configs': {'key': 'nodeConfigs', 'type': '{NodeConfig}'},
        'admin_user_info': {'key': 'adminUserInfo', 'type': 'AdminUserConfig'},
        'enable_software_encryption_at_rest': {'key': 'enableSoftwareEncryptionAtRest', 'type': 'bool'},
    }

    def __init__(self, name, ntp_servers, dns_nameservers, node_configs, admin_user_info, dns_search_domains=None, enable_software_encryption_at_rest=None):
        self.name = name
        self.ntp_servers = ntp_servers
        self.dns_nameservers = dns_nameservers
        self.dns_search_domains = dns_search_domains
        self.node_configs = node_configs
        self.admin_user_info = admin_user_info
        self.enable_software_encryption_at_rest = enable_software_encryption_at_rest
