# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClusterConfigRec(Model):
    """ClusterConfigRec.

    :param status:
    :type status: str
    :param id:
    :type id: long
    """

    _validation = {
        'status': {'required': True},
        'id': {'required': True},
    }

    _attribute_map = {
        'status': {'key': 'status', 'type': 'str'},
        'id': {'key': 'id', 'type': 'long'},
    }

    def __init__(self, status, id):
        self.status = status
        self.id = id
