# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DecommissionNodeConfig(Model):
    """DecommissionNodeConfig.

    :param node_id:
    :type node_id: str
    :param min_tolerable_node_failures: Specifies the number of remaining
     nodes that can fail without impact on data availability and consistency,
     after a specified node is decommissioned and removed. For example, setting
     the value to 1 means that a node can only be decommissioned if, after the
     decommission, the Rubrik cluster can lose 1 additional node and still
     continue normal operations.
    :type min_tolerable_node_failures: int
    """

    _validation = {
        'node_id': {'required': True},
    }

    _attribute_map = {
        'node_id': {'key': 'nodeId', 'type': 'str'},
        'min_tolerable_node_failures': {'key': 'minTolerableNodeFailures', 'type': 'int'},
    }

    def __init__(self, node_id, min_tolerable_node_failures=None):
        self.node_id = node_id
        self.min_tolerable_node_failures = min_tolerable_node_failures
