# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FetchUpgradeStatus(Model):
    """FetchUpgradeStatus.

    :param status:
    :type status: str
    :param bytes_read:
    :type bytes_read: str
    :param file_size:
    :type file_size: str
    """

    _validation = {
        'status': {'required': True},
        'bytes_read': {'required': True},
        'file_size': {'required': True},
    }

    _attribute_map = {
        'status': {'key': 'status', 'type': 'str'},
        'bytes_read': {'key': 'bytesRead', 'type': 'str'},
        'file_size': {'key': 'fileSize', 'type': 'str'},
    }

    def __init__(self, status, bytes_read, file_size):
        self.status = status
        self.bytes_read = bytes_read
        self.file_size = file_size
