# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FileVersion(Model):
    """FileVersion.

    :param last_modified:
    :type last_modified: str
    :param size:
    :type size: long
    :param snapshot_id: The snapshot this file belongs to
    :type snapshot_id: str
    :param file_mode: The type of file, either a regular file or a directory
    :type file_mode: str
    :param source: The location where the file is stored, either in the cloud
     or locally
    :type source: str
    """

    _attribute_map = {
        'last_modified': {'key': 'lastModified', 'type': 'str'},
        'size': {'key': 'size', 'type': 'long'},
        'snapshot_id': {'key': 'snapshotId', 'type': 'str'},
        'file_mode': {'key': 'fileMode', 'type': 'str'},
        'source': {'key': 'source', 'type': 'str'},
    }

    def __init__(self, last_modified=None, size=None, snapshot_id=None, file_mode=None, source=None):
        self.last_modified = last_modified
        self.size = size
        self.snapshot_id = snapshot_id
        self.file_mode = file_mode
        self.source = source
