# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .restore_path_pair import RestorePathPair


class FilesetRestorePathPair(RestorePathPair):
    """FilesetRestorePathPair.

    :param path: Original file path to be restored
    :type path: str
    :param restore_path: Directory of the folder to copy files into. If this
     is empty, file will be restored back into original directory.
    :type restore_path: str
    """

    _validation = {
        'path': {'required': True},
    }

    def __init__(self, path, restore_path=None):
        super(FilesetRestorePathPair, self).__init__(path=path, restore_path=restore_path)
