# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FloatingIp(Model):
    """FloatingIp.

    :param ip:
    :type ip: str
    :param node_id:
    :type node_id: str
    """

    _validation = {
        'ip': {'required': True},
        'node_id': {'required': True},
    }

    _attribute_map = {
        'ip': {'key': 'ip', 'type': 'str'},
        'node_id': {'key': 'nodeId', 'type': 'str'},
    }

    def __init__(self, ip, node_id):
        self.ip = ip
        self.node_id = node_id
