# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GlobalShieldConfig(Model):
    """GlobalShieldConfig.

    :param authorization_race_initial_range_for_back_off_in_ms: Initial range
     for exponential backoff for manipulation of explicit authorizations
    :type authorization_race_initial_range_for_back_off_in_ms: int
    :param authorization_race_max_retry_attempts: Number of retries for
     manipulation of explicit authorizations
    :type authorization_race_max_retry_attempts: int
    :param client_ssl_cipher_suites: SSL cipher suites enabled with a client
     socket in order of preference, colon(:) separated.
    :type client_ssl_cipher_suites: str
    :param group_membership_cache_refresh_secs: Interval at which a user's
     group membership is refreshed from its auth domain
    :type group_membership_cache_refresh_secs: int
    :param group_membership_cache_eviction_secs: Period of inactivity after
     which a user's group membership is evicted from the cache
    :type group_membership_cache_eviction_secs: int
    :param ldap_query_delay_in_ms: Delay in ms for LDAP queries (for
     performance simulation)
    :type ldap_query_delay_in_ms: int
    :param ldaps_tls_protocol: Protocol to use for LDAPS connections. See
     <http://docs.oracle.com/javase/7/docs/technotes/guides/security/
     StandardNames.html#SSLContext> for more details.
    :type ldaps_tls_protocol: str
    :param principal_search_api_cache_ttl_secs: Cache TTL for
     /principal_search endpoint (in seconds)
    :type principal_search_api_cache_ttl_secs: int
    :param send_stack_trace_in_server_error_rest_response: Flag determining
     whether stack traces should be sent along with the '500 server error'
     response.
    :type send_stack_trace_in_server_error_rest_response: bool
    :param server_ssl_cipher_suites: SSL cipher suites enabled with a server
     socket in order of preference, colon(:) separated
    :type server_ssl_cipher_suites: str
    :param is_software_encryption_at_rest_enabled: Flag determining whether
     software encryption at rest is enabled.
    :type is_software_encryption_at_rest_enabled: bool
    :param spray_minumum_tls_version: Minimum TLS Version for Spray server.
     Allowed values are TLSv1, TLSv1.1, TSLv1.2
    :type spray_minumum_tls_version: str
    :param spray_server_tls_cipher_suites: TLS cipher suites enabled with a
     server socket for spray server in order of preference, colon(:) separated
    :type spray_server_tls_cipher_suites: str
    :param registration_public_rsa_key: Path to public RSA key for cluster
     registration service.
    :type registration_public_rsa_key: str
    :param support_tunnel_inactivity_timeout_in_seconds: Inactivity timeout
     after which support tunnel is automatically closed. Activity is defined as
     executing at least one command when logged in via SSH as the rksupport
     user.
    :type support_tunnel_inactivity_timeout_in_seconds: int
    :param verify_encryption_keys_frequency_in_minutes: Frequency in minutes
     to run job to verify KMIP connectivity (if enabled).
    :type verify_encryption_keys_frequency_in_minutes: int
    :param csr_rsa_key_bits: Number of bits used for RSA key in certificate
     signing request
    :type csr_rsa_key_bits: int
    :param csr_message_digest_algorithm: Message digest algorithm used in
     certificate signing request
    :type csr_message_digest_algorithm: str
    """

    _attribute_map = {
        'authorization_race_initial_range_for_back_off_in_ms': {'key': 'authorizationRaceInitialRangeForBackOffInMs', 'type': 'int'},
        'authorization_race_max_retry_attempts': {'key': 'authorizationRaceMaxRetryAttempts', 'type': 'int'},
        'client_ssl_cipher_suites': {'key': 'clientSslCipherSuites', 'type': 'str'},
        'group_membership_cache_refresh_secs': {'key': 'groupMembershipCacheRefreshSecs', 'type': 'int'},
        'group_membership_cache_eviction_secs': {'key': 'groupMembershipCacheEvictionSecs', 'type': 'int'},
        'ldap_query_delay_in_ms': {'key': 'ldapQueryDelayInMs', 'type': 'int'},
        'ldaps_tls_protocol': {'key': 'ldapsTlsProtocol', 'type': 'str'},
        'principal_search_api_cache_ttl_secs': {'key': 'principalSearchApiCacheTtlSecs', 'type': 'int'},
        'send_stack_trace_in_server_error_rest_response': {'key': 'sendStackTraceInServerErrorRestResponse', 'type': 'bool'},
        'server_ssl_cipher_suites': {'key': 'serverSslCipherSuites', 'type': 'str'},
        'is_software_encryption_at_rest_enabled': {'key': 'isSoftwareEncryptionAtRestEnabled', 'type': 'bool'},
        'spray_minumum_tls_version': {'key': 'sprayMinumumTlsVersion', 'type': 'str'},
        'spray_server_tls_cipher_suites': {'key': 'sprayServerTlsCipherSuites', 'type': 'str'},
        'registration_public_rsa_key': {'key': 'registrationPublicRSAKey', 'type': 'str'},
        'support_tunnel_inactivity_timeout_in_seconds': {'key': 'supportTunnelInactivityTimeoutInSeconds', 'type': 'int'},
        'verify_encryption_keys_frequency_in_minutes': {'key': 'verifyEncryptionKeysFrequencyInMinutes', 'type': 'int'},
        'csr_rsa_key_bits': {'key': 'csrRsaKeyBits', 'type': 'int'},
        'csr_message_digest_algorithm': {'key': 'csrMessageDigestAlgorithm', 'type': 'str'},
    }

    def __init__(self, authorization_race_initial_range_for_back_off_in_ms=None, authorization_race_max_retry_attempts=None, client_ssl_cipher_suites=None, group_membership_cache_refresh_secs=None, group_membership_cache_eviction_secs=None, ldap_query_delay_in_ms=None, ldaps_tls_protocol=None, principal_search_api_cache_ttl_secs=None, send_stack_trace_in_server_error_rest_response=None, server_ssl_cipher_suites=None, is_software_encryption_at_rest_enabled=None, spray_minumum_tls_version=None, spray_server_tls_cipher_suites=None, registration_public_rsa_key=None, support_tunnel_inactivity_timeout_in_seconds=None, verify_encryption_keys_frequency_in_minutes=None, csr_rsa_key_bits=None, csr_message_digest_algorithm=None):
        self.authorization_race_initial_range_for_back_off_in_ms = authorization_race_initial_range_for_back_off_in_ms
        self.authorization_race_max_retry_attempts = authorization_race_max_retry_attempts
        self.client_ssl_cipher_suites = client_ssl_cipher_suites
        self.group_membership_cache_refresh_secs = group_membership_cache_refresh_secs
        self.group_membership_cache_eviction_secs = group_membership_cache_eviction_secs
        self.ldap_query_delay_in_ms = ldap_query_delay_in_ms
        self.ldaps_tls_protocol = ldaps_tls_protocol
        self.principal_search_api_cache_ttl_secs = principal_search_api_cache_ttl_secs
        self.send_stack_trace_in_server_error_rest_response = send_stack_trace_in_server_error_rest_response
        self.server_ssl_cipher_suites = server_ssl_cipher_suites
        self.is_software_encryption_at_rest_enabled = is_software_encryption_at_rest_enabled
        self.spray_minumum_tls_version = spray_minumum_tls_version
        self.spray_server_tls_cipher_suites = spray_server_tls_cipher_suites
        self.registration_public_rsa_key = registration_public_rsa_key
        self.support_tunnel_inactivity_timeout_in_seconds = support_tunnel_inactivity_timeout_in_seconds
        self.verify_encryption_keys_frequency_in_minutes = verify_encryption_keys_frequency_in_minutes
        self.csr_rsa_key_bits = csr_rsa_key_bits
        self.csr_message_digest_algorithm = csr_message_digest_algorithm
