# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .base_guest_credential import BaseGuestCredential


class GuestCredentialDefinition(BaseGuestCredential):
    """GuestCredentialDefinition.

    :param username: Username for the account used to login to the VM guest
     OS. To include a domain, use the format <domain>\\<username>.
    :type username: str
    :param password: Password for the account used to login to the VM guest
     OS.
    :type password: str
    :param domain:
    :type domain: str
    """

    _validation = {
        'username': {'required': True},
        'password': {'required': True},
    }

    _attribute_map = {
        'username': {'key': 'username', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'domain': {'key': 'domain', 'type': 'str'},
    }

    def __init__(self, username, password, domain=None):
        super(GuestCredentialDefinition, self).__init__(username=username, password=password)
        self.domain = domain
