# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HypervHostDetail(Model):
    """HypervHostDetail.

    :param configured_sla_domain_id: Assign this VM to the given SLA domain.
    :type configured_sla_domain_id: str
    :param hostname: IP Address or the hostname using which the host was added
    :type hostname: str
    """

    _attribute_map = {
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
        'hostname': {'key': 'hostname', 'type': 'str'},
    }

    def __init__(self, configured_sla_domain_id=None, hostname=None):
        self.configured_sla_domain_id = configured_sla_domain_id
        self.hostname = hostname
