# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HypervUpdateMountConfig(Model):
    """HypervUpdateMountConfig.

    :param power_status: True to power on, false to power off
    :type power_status: bool
    """

    _validation = {
        'power_status': {'required': True},
    }

    _attribute_map = {
        'power_status': {'key': 'powerStatus', 'type': 'bool'},
    }

    def __init__(self, power_status):
        self.power_status = power_status
