# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class InternalSnapshotArchiveGarbageCollectStatusConfig(Model):
    """InternalSnapshotArchiveGarbageCollectStatusConfig.

    :param snapshot_date_tuples: Snapshots to check for garbage collection,
     specified as <snapshotID>:::<snapshotDate>
    :type snapshot_date_tuples: list of str
    :param snappable_id:
    :type snappable_id: str
    :param location_id:
    :type location_id: str
    """

    _validation = {
        'snapshot_date_tuples': {'required': True},
        'snappable_id': {'required': True},
        'location_id': {'required': True},
    }

    _attribute_map = {
        'snapshot_date_tuples': {'key': 'snapshotDateTuples', 'type': '[str]'},
        'snappable_id': {'key': 'snappableId', 'type': 'str'},
        'location_id': {'key': 'locationId', 'type': 'str'},
    }

    def __init__(self, snapshot_date_tuples, snappable_id, location_id):
        self.snapshot_date_tuples = snapshot_date_tuples
        self.snappable_id = snappable_id
        self.location_id = location_id
