# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IpmiAccess(Model):
    """IpmiAccess.

    :param https:
    :type https: bool
    :param i_kvm:
    :type i_kvm: bool
    :param virtual_media:
    :type virtual_media: bool
    :param ssh:
    :type ssh: bool
    """

    _validation = {
        'https': {'required': True},
        'i_kvm': {'required': True},
        'virtual_media': {'required': True},
        'ssh': {'required': True},
    }

    _attribute_map = {
        'https': {'key': 'https', 'type': 'bool'},
        'i_kvm': {'key': 'iKvm', 'type': 'bool'},
        'virtual_media': {'key': 'virtualMedia', 'type': 'bool'},
        'ssh': {'key': 'ssh', 'type': 'bool'},
    }

    def __init__(self, https, i_kvm, virtual_media, ssh):
        self.https = https
        self.i_kvm = i_kvm
        self.virtual_media = virtual_media
        self.ssh = ssh
