# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IscsiPortalInfo(Model):
    """IscsiPortalInfo.

    :param host: Resolvable hostname or IP address of the iSCSI portal
    :type host: str
    :param port: Inbound port on the iSCSI portal, default is 3260
    :type port: str
    :param username: Username for CHAP authentication on the iSCSI device. No
     value for an unauthenticated connection
    :type username: str
    :param password: Password for CHAP authentication on the iSCSI device. No
     value for an unauthenticated connection
    :type password: str
    :param username_in: Username for CHAP authentication on the Rubrik
     cluster. No value for an unauthenticate or unidirectional authenticated
     connection
    :type username_in: str
    :param password_in: Password Username for CHAP authentication on the
     Rubrik cluster. No value for an unauthenticate or unidirectional
     authenticated connection
    :type password_in: str
    """

    _validation = {
        'host': {'required': True},
        'port': {'required': True},
    }

    _attribute_map = {
        'host': {'key': 'host', 'type': 'str'},
        'port': {'key': 'port', 'type': 'str'},
        'username': {'key': 'username', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'username_in': {'key': 'usernameIn', 'type': 'str'},
        'password_in': {'key': 'passwordIn', 'type': 'str'},
    }

    def __init__(self, host, port, username=None, password=None, username_in=None, password_in=None):
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        self.username_in = username_in
        self.password_in = password_in
