# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LocalBlobstoreConfig(Model):
    """LocalBlobstoreConfig.

    :param consolidate_job_in_memory_sem_shares: Maximum number of concurrent
     consolidate jobs per node
    :type consolidate_job_in_memory_sem_shares: int
    :param cross_job_in_memory_sem_shares: Maximum number of concurrent cross
     jobs per node
    :type cross_job_in_memory_sem_shares: int
    :param reverse_job_in_memory_sem_shares: Maximum number of concurrent
     reverse jobs per node
    :type reverse_job_in_memory_sem_shares: int
    """

    _attribute_map = {
        'consolidate_job_in_memory_sem_shares': {'key': 'consolidateJobInMemorySemShares', 'type': 'int'},
        'cross_job_in_memory_sem_shares': {'key': 'crossJobInMemorySemShares', 'type': 'int'},
        'reverse_job_in_memory_sem_shares': {'key': 'reverseJobInMemorySemShares', 'type': 'int'},
    }

    def __init__(self, consolidate_job_in_memory_sem_shares=None, cross_job_in_memory_sem_shares=None, reverse_job_in_memory_sem_shares=None):
        self.consolidate_job_in_memory_sem_shares = consolidate_job_in_memory_sem_shares
        self.cross_job_in_memory_sem_shares = cross_job_in_memory_sem_shares
        self.reverse_job_in_memory_sem_shares = reverse_job_in_memory_sem_shares
