# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LocalThorConfig(Model):
    """LocalThorConfig.

    :param s3_max_thread_count_for_upload: Max number of threads used to
     upload a file to S3
    :type s3_max_thread_count_for_upload: int
    :param azure_max_thread_count_for_upload: Max number of threads used to
     upload a file to Azure
    :type azure_max_thread_count_for_upload: int
    :param nfs_max_thread_count_for_upload: Max number of threads used to
     upload a file to NFS
    :type nfs_max_thread_count_for_upload: int
    :param archival_service_cache_size: Number of entries in the archival
     service Cache
    :type archival_service_cache_size: int
    :param max_num_convert_to_stream_optimized_vmdk_format_jobs: Max number of
     ConvertToStreamOptimizedVmdkFormat jobs allowed per node
    :type max_num_convert_to_stream_optimized_vmdk_format_jobs: int
    :param max_num_upload_file_jobs: Max number of UploadFile jobs allowed per
     node
    :type max_num_upload_file_jobs: int
    """

    _attribute_map = {
        's3_max_thread_count_for_upload': {'key': 's3MaxThreadCountForUpload', 'type': 'int'},
        'azure_max_thread_count_for_upload': {'key': 'azureMaxThreadCountForUpload', 'type': 'int'},
        'nfs_max_thread_count_for_upload': {'key': 'nfsMaxThreadCountForUpload', 'type': 'int'},
        'archival_service_cache_size': {'key': 'archivalServiceCacheSize', 'type': 'int'},
        'max_num_convert_to_stream_optimized_vmdk_format_jobs': {'key': 'maxNumConvertToStreamOptimizedVmdkFormatJobs', 'type': 'int'},
        'max_num_upload_file_jobs': {'key': 'maxNumUploadFileJobs', 'type': 'int'},
    }

    def __init__(self, s3_max_thread_count_for_upload=None, azure_max_thread_count_for_upload=None, nfs_max_thread_count_for_upload=None, archival_service_cache_size=None, max_num_convert_to_stream_optimized_vmdk_format_jobs=None, max_num_upload_file_jobs=None):
        self.s3_max_thread_count_for_upload = s3_max_thread_count_for_upload
        self.azure_max_thread_count_for_upload = azure_max_thread_count_for_upload
        self.nfs_max_thread_count_for_upload = nfs_max_thread_count_for_upload
        self.archival_service_cache_size = archival_service_cache_size
        self.max_num_convert_to_stream_optimized_vmdk_format_jobs = max_num_convert_to_stream_optimized_vmdk_format_jobs
        self.max_num_upload_file_jobs = max_num_upload_file_jobs
