# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ManagedObjectProperties(Model):
    """ManagedObjectProperties.

    :param hostname:
    :type hostname: str
    :param operating_system:
    :type operating_system: str
    :param operating_system_type:
    :type operating_system_type: str
    """

    _attribute_map = {
        'hostname': {'key': 'hostname', 'type': 'str'},
        'operating_system': {'key': 'operatingSystem', 'type': 'str'},
        'operating_system_type': {'key': 'operatingSystemType', 'type': 'str'},
    }

    def __init__(self, hostname=None, operating_system=None, operating_system_type=None):
        self.hostname = hostname
        self.operating_system = operating_system
        self.operating_system_type = operating_system_type
