# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .managed_volume_snapshot_export_summary import ManagedVolumeSnapshotExportSummary


class ManagedVolumeSnapshotExportDetail(ManagedVolumeSnapshotExportSummary):
    """ManagedVolumeSnapshotExportDetail.

    :param is_active: Is export active.
    :type is_active: bool
    :param channels: Channels of this export.
    :type channels: list of :class:`ManagedVolumeChannelConfig
     <rubriklib_int.models.ManagedVolumeChannelConfig>`
    :param config:
    :type config: :class:`ManagedVolumeExportConfig
     <rubriklib_int.models.ManagedVolumeExportConfig>`
    :param id: ID of managed volume snapshot export
    :type id: str
    :param snapshot_id: Snapshot this export is based off.
    :type snapshot_id: str
    :param snapshot_date: Date of the snapshot this export is based off.
    :type snapshot_date: datetime
    :param source_managed_volume_id: ID of the managed volume this export
     belongs to.
    :type source_managed_volume_id: str
    :param source_managed_volume_name: Name of the managed volume this export
     belongs to.
    :type source_managed_volume_name: str
    :param exported_date: Exported date of the managed volume snapshot.
    :type exported_date: datetime
    """

    _validation = {
        'is_active': {'required': True},
        'channels': {'required': True},
        'config': {'required': True},
    }

    def __init__(self, is_active, channels, config, id=None, snapshot_id=None, snapshot_date=None, source_managed_volume_id=None, source_managed_volume_name=None, exported_date=None):
        super(ManagedVolumeSnapshotExportDetail, self).__init__(is_active=is_active, channels=channels, config=config, id=id, snapshot_id=snapshot_id, snapshot_date=snapshot_date, source_managed_volume_id=source_managed_volume_id, source_managed_volume_name=source_managed_volume_name, exported_date=exported_date)
