# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ManagedObjectLocations(Model):
    """ManagedObjectLocations.

    :param folder: VMware folder hierarchy
    :type folder: list of :class:`ManagedObjectAncestor
     <rubriklib_int.models.ManagedObjectAncestor>`
    :param infrastructure: Infrastructure hierarchy (cluster/host/server/VM)
    :type infrastructure: list of :class:`ManagedObjectAncestor
     <rubriklib_int.models.ManagedObjectAncestor>`
    :param physical: Physical host hierarchy
    :type physical: list of :class:`ManagedObjectAncestor
     <rubriklib_int.models.ManagedObjectAncestor>`
    """

    _attribute_map = {
        'folder': {'key': 'folder', 'type': '[ManagedObjectAncestor]'},
        'infrastructure': {'key': 'infrastructure', 'type': '[ManagedObjectAncestor]'},
        'physical': {'key': 'physical', 'type': '[ManagedObjectAncestor]'},
    }

    def __init__(self, folder=None, infrastructure=None, physical=None):
        self.folder = folder
        self.infrastructure = infrastructure
        self.physical = physical
