# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MssqlSnappableId(Model):
    """MssqlSnappableId.

    :param snappable_id: ID of snappable
    :type snappable_id: str
    """

    _validation = {
        'snappable_id': {'required': True},
    }

    _attribute_map = {
        'snappable_id': {'key': 'snappableId', 'type': 'str'},
    }

    def __init__(self, snappable_id):
        self.snappable_id = snappable_id
