# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .request_failed_exception import RequestFailedException


class MssqlDbAssignToSlaConflictResponse(RequestFailedException):
    """MssqlDbAssignToSlaConflictResponse.

    :param error_type:
    :type error_type: str
    :param message:
    :type message: str
    :param code:
    :type code: str
    :param param:
    :type param: str
    :param sla_conflict_information:
    :type sla_conflict_information: :class:`MssqlDbSlaConflictInfo
     <rubriklib_int.models.MssqlDbSlaConflictInfo>`
    """

    _validation = {
        'error_type': {'required': True},
        'message': {'required': True},
    }

    _attribute_map = {
        'error_type': {'key': 'errorType', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'param': {'key': 'param', 'type': 'str'},
        'sla_conflict_information': {'key': 'slaConflictInformation', 'type': 'MssqlDbSlaConflictInfo'},
    }

    def __init__(self, error_type, message, code=None, param=None, sla_conflict_information=None):
        super(MssqlDbAssignToSlaConflictResponse, self).__init__(error_type=error_type, message=message, code=code, param=param)
        self.sla_conflict_information = sla_conflict_information
