# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NodeStatus(Model):
    """NodeStatus.

    :param id:
    :type id: str
    :param brik_id:
    :type brik_id: str
    :param status:
    :type status: str
    :param ip_address:
    :type ip_address: str
    :param needs_inspection:
    :type needs_inspection: bool
    """

    _validation = {
        'id': {'required': True},
        'brik_id': {'required': True},
        'status': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'brik_id': {'key': 'brikId', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'ip_address': {'key': 'ipAddress', 'type': 'str'},
        'needs_inspection': {'key': 'needsInspection', 'type': 'bool'},
    }

    def __init__(self, id, brik_id, status, ip_address=None, needs_inspection=None):
        self.id = id
        self.brik_id = brik_id
        self.status = status
        self.ip_address = ip_address
        self.needs_inspection = needs_inspection
