# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NutanixVmDetail(Model):
    """NutanixVmDetail.

    :param configured_sla_domain_id: Assign this VM to the given SLA domain.
    :type configured_sla_domain_id: str
    :param is_paused: Whether backup/archival/replication is paused for this
     VM
    :type is_paused: bool
    :param nutanix_cluster_id: The ID of the Nutanix cluster to which this VM
     belongs
    :type nutanix_cluster_id: str
    :param nutanix_cluster_name: The name of the Nutanix cluster to which this
     VM belongs
    :type nutanix_cluster_name: str
    :param is_relic: Whether this Nutanix VM is currently present on the
     Nutanix cluster
    :type is_relic: bool
    :param blackout_window_status:
    :type blackout_window_status: :class:`BlackoutWindowStatus
     <rubriklib_int.models.BlackoutWindowStatus>`
    :param blackout_windows:
    :type blackout_windows: :class:`BlackoutWindows
     <rubriklib_int.models.BlackoutWindows>`
    """

    _attribute_map = {
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
        'is_paused': {'key': 'isPaused', 'type': 'bool'},
        'nutanix_cluster_id': {'key': 'nutanixClusterId', 'type': 'str'},
        'nutanix_cluster_name': {'key': 'nutanixClusterName', 'type': 'str'},
        'is_relic': {'key': 'isRelic', 'type': 'bool'},
        'blackout_window_status': {'key': 'blackoutWindowStatus', 'type': 'BlackoutWindowStatus'},
        'blackout_windows': {'key': 'blackoutWindows', 'type': 'BlackoutWindows'},
    }

    def __init__(self, configured_sla_domain_id=None, is_paused=None, nutanix_cluster_id=None, nutanix_cluster_name=None, is_relic=None, blackout_window_status=None, blackout_windows=None):
        self.configured_sla_domain_id = configured_sla_domain_id
        self.is_paused = is_paused
        self.nutanix_cluster_id = nutanix_cluster_id
        self.nutanix_cluster_name = nutanix_cluster_name
        self.is_relic = is_relic
        self.blackout_window_status = blackout_window_status
        self.blackout_windows = blackout_windows
