# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ObjectStoreUpdateDefinition(Model):
    """ObjectStoreUpdateDefinition.

    :param name:
    :type name: str
    :param access_key:
    :type access_key: str
    :param secret_key:
    :type secret_key: str
    :param endpoint:
    :type endpoint: str
    :param num_buckets:
    :type num_buckets: long
    :param is_compute_enabled:
    :type is_compute_enabled: bool
    :param compute_security_group_id:
    :type compute_security_group_id: str
    :param storage_class:
    :type storage_class: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'access_key': {'key': 'accessKey', 'type': 'str'},
        'secret_key': {'key': 'secretKey', 'type': 'str'},
        'endpoint': {'key': 'endpoint', 'type': 'str'},
        'num_buckets': {'key': 'numBuckets', 'type': 'long'},
        'is_compute_enabled': {'key': 'isComputeEnabled', 'type': 'bool'},
        'compute_security_group_id': {'key': 'computeSecurityGroupId', 'type': 'str'},
        'storage_class': {'key': 'storageClass', 'type': 'str'},
    }

    def __init__(self, name=None, access_key=None, secret_key=None, endpoint=None, num_buckets=None, is_compute_enabled=None, compute_security_group_id=None, storage_class=None):
        self.name = name
        self.access_key = access_key
        self.secret_key = secret_key
        self.endpoint = endpoint
        self.num_buckets = num_buckets
        self.is_compute_enabled = is_compute_enabled
        self.compute_security_group_id = compute_security_group_id
        self.storage_class = storage_class
