# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProtectionDetail(Model):
    """ProtectionDetail.

    :param managed_id:
    :type managed_id: str
    :param id:
    :type id: str
    :param object_type:
    :type object_type: str
    :param name:
    :type name: str
    :param configured_sla_domain_id:
    :type configured_sla_domain_id: str
    :param effective_sla_domain_id:
    :type effective_sla_domain_id: str
    :param effective_sla_domain_name:
    :type effective_sla_domain_name: str
    :param effective_sla_source:
    :type effective_sla_source: :class:`ManagedObject
     <rubriklib_int.models.ManagedObject>`
    """

    _validation = {
        'managed_id': {'required': True},
        'id': {'required': True},
        'object_type': {'required': True},
        'name': {'required': True},
        'configured_sla_domain_id': {'required': True},
    }

    _attribute_map = {
        'managed_id': {'key': 'managedId', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'object_type': {'key': 'objectType', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
        'effective_sla_domain_id': {'key': 'effectiveSlaDomainId', 'type': 'str'},
        'effective_sla_domain_name': {'key': 'effectiveSlaDomainName', 'type': 'str'},
        'effective_sla_source': {'key': 'effectiveSlaSource', 'type': 'ManagedObject'},
    }

    def __init__(self, managed_id, id, object_type, name, configured_sla_domain_id, effective_sla_domain_id=None, effective_sla_domain_name=None, effective_sla_source=None):
        self.managed_id = managed_id
        self.id = id
        self.object_type = object_type
        self.name = name
        self.configured_sla_domain_id = configured_sla_domain_id
        self.effective_sla_domain_id = effective_sla_domain_id
        self.effective_sla_domain_name = effective_sla_domain_name
        self.effective_sla_source = effective_sla_source
