# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProxyConfig(Model):
    """ProxyConfig.

    :param host:
    :type host: str
    :param port:
    :type port: int
    :param protocol:
    :type protocol: str
    :param username:
    :type username: str
    :param password:
    :type password: str
    """

    _validation = {
        'host': {'required': True},
        'protocol': {'required': True},
    }

    _attribute_map = {
        'host': {'key': 'host', 'type': 'str'},
        'port': {'key': 'port', 'type': 'int'},
        'protocol': {'key': 'protocol', 'type': 'str'},
        'username': {'key': 'username', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
    }

    def __init__(self, host, protocol, port=None, username=None, password=None):
        self.host = host
        self.port = port
        self.protocol = protocol
        self.username = username
        self.password = password
