# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .qstar_location_definition import QstarLocationDefinition


class QstarLocationDefinitionWithCredential(QstarLocationDefinition):
    """QstarLocationDefinitionWithCredential.

    :param host: Hostname of the QStar server
    :type host: str
    :param integral_volume: QStar integral volume to mount
    :type integral_volume: str
    :param bucket: Bucket under the integral volume. The name cannot contain
     whitespace or _\\\\/*?%.:|<>
    :type bucket: str
    :param name: Name of this archival location
    :type name: str
    :param mount_protocol: Protocol to connect with the QStar server. Possible
     values include: 'NFS', 'CIFS'
    :type mount_protocol: str or :class:`enum <rubriklib_int.models.enum>`
    :param nfs_version: NFS protocol version to communicate with QStar server
     when using NFS mount protocol
    :type nfs_version: int
    :param other_nfs_options: Additional NFS options when using NFS protocol
    :type other_nfs_options: str
    :param other_cifs_options: Additional CIFS options when using CIFS
     protocol
    :type other_cifs_options: str
    :param username: User name credentials to access the QStar server
    :type username: str
    :param password: Password credentials to access the QStar server
    :type password: str
    :param encryption_password: Password for encrypting the QStar archival
     location.
    :type encryption_password: str
    """

    _validation = {
        'host': {'required': True},
        'integral_volume': {'required': True},
        'bucket': {'required': True},
        'name': {'required': True},
        'mount_protocol': {'required': True},
    }

    _attribute_map = {
        'host': {'key': 'host', 'type': 'str'},
        'integral_volume': {'key': 'integralVolume', 'type': 'str'},
        'bucket': {'key': 'bucket', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'mount_protocol': {'key': 'mountProtocol', 'type': 'str'},
        'nfs_version': {'key': 'nfsVersion', 'type': 'int'},
        'other_nfs_options': {'key': 'otherNfsOptions', 'type': 'str'},
        'other_cifs_options': {'key': 'otherCifsOptions', 'type': 'str'},
        'username': {'key': 'username', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'encryption_password': {'key': 'encryptionPassword', 'type': 'str'},
    }

    def __init__(self, host, integral_volume, bucket, name, mount_protocol, nfs_version=None, other_nfs_options=None, other_cifs_options=None, username=None, password=None, encryption_password=None):
        super(QstarLocationDefinitionWithCredential, self).__init__(host=host, integral_volume=integral_volume, bucket=bucket, name=name, mount_protocol=mount_protocol, nfs_version=nfs_version, other_nfs_options=other_nfs_options, other_cifs_options=other_cifs_options)
        self.username = username
        self.password = password
        self.encryption_password = encryption_password
