# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RecommissionNodeStatus(Model):
    """RecommissionNodeStatus.

    :param status:
    :type status: str
    :param start_services:
    :type start_services: str
    :param cassandra_setup:
    :type cassandra_setup: str
    """

    _validation = {
        'status': {'required': True},
        'start_services': {'required': True},
        'cassandra_setup': {'required': True},
    }

    _attribute_map = {
        'status': {'key': 'status', 'type': 'str'},
        'start_services': {'key': 'startServices', 'type': 'str'},
        'cassandra_setup': {'key': 'cassandraSetup', 'type': 'str'},
    }

    def __init__(self, status, start_services, cassandra_setup):
        self.status = status
        self.start_services = start_services
        self.cassandra_setup = cassandra_setup
