# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RemoveObjectStoreBucketRequest(Model):
    """RemoveObjectStoreBucketRequest.

    :param bucket_prefix:
    :type bucket_prefix: str
    :param older_than_hours:
    :type older_than_hours: int
    :param location_definition:
    :type location_definition: :class:`ObjectStoreLocationDefinition
     <rubriklib_int.models.ObjectStoreLocationDefinition>`
    """

    _validation = {
        'bucket_prefix': {'required': True},
        'older_than_hours': {'required': True},
        'location_definition': {'required': True},
    }

    _attribute_map = {
        'bucket_prefix': {'key': 'bucketPrefix', 'type': 'str'},
        'older_than_hours': {'key': 'olderThanHours', 'type': 'int'},
        'location_definition': {'key': 'locationDefinition', 'type': 'ObjectStoreLocationDefinition'},
    }

    def __init__(self, bucket_prefix, older_than_hours, location_definition):
        self.bucket_prefix = bucket_prefix
        self.older_than_hours = older_than_hours
        self.location_definition = location_definition
