# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReplicationSpec(Model):
    """ReplicationSpec.

    :param location_id:
    :type location_id: str
    :param retention_limit:
    :type retention_limit: long
    """

    _validation = {
        'location_id': {'required': True},
        'retention_limit': {'required': True},
    }

    _attribute_map = {
        'location_id': {'key': 'locationId', 'type': 'str'},
        'retention_limit': {'key': 'retentionLimit', 'type': 'long'},
    }

    def __init__(self, location_id, retention_limit):
        self.location_id = location_id
        self.retention_limit = retention_limit
