# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReportUpdate(Model):
    """ReportUpdate.

    :param name: The name of the report.
    :type name: str
    :param filters: Filter properties to update.
    :type filters: :class:`FilterSummary <rubriklib_int.models.FilterSummary>`
    :param chart0: Chart0 properties to update.
    :type chart0: :class:`ChartSummary <rubriklib_int.models.ChartSummary>`
    :param chart1: Chart1 properties to update.
    :type chart1: :class:`ChartSummary <rubriklib_int.models.ChartSummary>`
    :param table: Table properties to update.
    :type table: :class:`TableSummary <rubriklib_int.models.TableSummary>`
    """

    _validation = {
        'name': {'required': True},
        'filters': {'required': True},
        'chart0': {'required': True},
        'chart1': {'required': True},
        'table': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'filters': {'key': 'filters', 'type': 'FilterSummary'},
        'chart0': {'key': 'chart0', 'type': 'ChartSummary'},
        'chart1': {'key': 'chart1', 'type': 'ChartSummary'},
        'table': {'key': 'table', 'type': 'TableSummary'},
    }

    def __init__(self, name, filters, chart0, chart1, table):
        self.name = name
        self.filters = filters
        self.chart0 = chart0
        self.chart1 = chart1
        self.table = table
