# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SlaDomainAssignmentInfo(Model):
    """SlaDomainAssignmentInfo.

    :param managed_ids:
    :type managed_ids: list of str
    """

    _validation = {
        'managed_ids': {'required': True},
    }

    _attribute_map = {
        'managed_ids': {'key': 'managedIds', 'type': '[str]'},
    }

    def __init__(self, managed_ids):
        self.managed_ids = managed_ids
