# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SlaFrequency(Model):
    """SlaFrequency.

    :param time_unit: Units for frequency and retention. Accepted values are
     Hourly, Daily, Weekly, Monthly, and Yearly.
    :type time_unit: str
    :param frequency:
    :type frequency: int
    :param retention:
    :type retention: int
    """

    _validation = {
        'time_unit': {'required': True},
        'frequency': {'required': True},
        'retention': {'required': True},
    }

    _attribute_map = {
        'time_unit': {'key': 'timeUnit', 'type': 'str'},
        'frequency': {'key': 'frequency', 'type': 'int'},
        'retention': {'key': 'retention', 'type': 'int'},
    }

    def __init__(self, time_unit, frequency, retention):
        self.time_unit = time_unit
        self.frequency = frequency
        self.retention = retention
