# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SlaStartTimeAttributes(Model):
    """SlaStartTimeAttributes.

    :param minutes:
    :type minutes: int
    :param hour:
    :type hour: int
    :param day_of_week:
    :type day_of_week: int
    """

    _validation = {
        'minutes': {'required': True},
        'hour': {'required': True},
    }

    _attribute_map = {
        'minutes': {'key': 'minutes', 'type': 'int'},
        'hour': {'key': 'hour', 'type': 'int'},
        'day_of_week': {'key': 'dayOfWeek', 'type': 'int'},
    }

    def __init__(self, minutes, hour, day_of_week=None):
        self.minutes = minutes
        self.hour = hour
        self.day_of_week = day_of_week
