# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UpgradeStatus(Model):
    """UpgradeStatus.

    :param status:
    :type status: str
    :param message:
    :type message: str
    """

    _validation = {
        'status': {'required': True},
        'message': {'required': True},
    }

    _attribute_map = {
        'status': {'key': 'status', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
    }

    def __init__(self, status, message):
        self.status = status
        self.message = message
