# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VirtualMachineBrief(Model):
    """VirtualMachineBrief.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param sla_domain_name: DEPRECATED: The name of the SLA domain this VM
     belongs to
    :type sla_domain_name: str
    :param effective_sla_domain_name: The name of the effective SLA domain for
     this VM
    :type effective_sla_domain_name: str
    """

    _validation = {
        'id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'sla_domain_name': {'key': 'slaDomainName', 'type': 'str'},
        'effective_sla_domain_name': {'key': 'effectiveSlaDomainName', 'type': 'str'},
    }

    def __init__(self, id, name=None, sla_domain_name=None, effective_sla_domain_name=None):
        self.id = id
        self.name = name
        self.sla_domain_name = sla_domain_name
        self.effective_sla_domain_name = effective_sla_domain_name
