# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VlanConfig(Model):
    """VlanConfig.

    :param vlan:
    :type vlan: int
    :param netmask: Netmask for addresses on this VLAN
    :type netmask: str
    :param interfaces: Network interfaces for each node
    :type interfaces: list of :class:`NodeIp <rubriklib_int.models.NodeIp>`
    """

    _validation = {
        'vlan': {'required': True},
        'netmask': {'required': True},
        'interfaces': {'required': True},
    }

    _attribute_map = {
        'vlan': {'key': 'vlan', 'type': 'int'},
        'netmask': {'key': 'netmask', 'type': 'str'},
        'interfaces': {'key': 'interfaces', 'type': '[NodeIp]'},
    }

    def __init__(self, vlan, netmask, interfaces):
        self.vlan = vlan
        self.netmask = netmask
        self.interfaces = interfaces
