---

- name: Validate the Rubrik Modules
  hosts: local
  connection: local
  vars_files:
    - ./variables.yml

  tasks:

    - name: Take a On Demand vSphere VM Snapshot
      rubrik_on_demand_snapshot:
        provider={{ credentials }}
        vsphere_vm_name={{ vsphere_vm_name }}
        sla_domain_name={{ sla_domain_name }}
        