# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClusterApiVersion(Model):
    """ClusterApiVersion.

    :param api_version: REST API version
    :type api_version: str
    """

    _validation = {
        'api_version': {'required': True},
    }

    _attribute_map = {
        'api_version': {'key': 'apiVersion', 'type': 'str'},
    }

    def __init__(self, api_version):
        self.api_version = api_version
