# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LsnRecoveryPoint(Model):
    """LsnRecoveryPoint.

    :param lsn: LSN of the recovery point.
    :type lsn: str
    :param recovery_fork_guid: Recovery fork GUID of the recovery point. If
     not provided, the recovery fork GUID of the latest snapshot is used.
    :type recovery_fork_guid: str
    """

    _attribute_map = {
        'lsn': {'key': 'lsn', 'type': 'str'},
        'recovery_fork_guid': {'key': 'recoveryForkGuid', 'type': 'str'},
    }

    def __init__(self, lsn=None, recovery_fork_guid=None):
        self.lsn = lsn
        self.recovery_fork_guid = recovery_fork_guid
