# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MountMssqlDbConfig(Model):
    """MountMssqlDbConfig.

    :param recovery_point:
    :type recovery_point: :class:`MssqlRecoveryPoint
     <rubriklib.models.MssqlRecoveryPoint>`
    :param mounted_database_name: Name to assign to the mounted database.
    :type mounted_database_name: str
    :param target_instance_id: ID of the SQL Server instance to mount the
     database on. For availability source databases, this must be specified.
     When unspecified for non-availability source databases, the source SQL
     Server instance is used.
    :type target_instance_id: str
    """

    _validation = {
        'recovery_point': {'required': True},
        'mounted_database_name': {'required': True},
    }

    _attribute_map = {
        'recovery_point': {'key': 'recoveryPoint', 'type': 'MssqlRecoveryPoint'},
        'mounted_database_name': {'key': 'mountedDatabaseName', 'type': 'str'},
        'target_instance_id': {'key': 'targetInstanceId', 'type': 'str'},
    }

    def __init__(self, recovery_point, mounted_database_name, target_instance_id=None):
        self.recovery_point = recovery_point
        self.mounted_database_name = mounted_database_name
        self.target_instance_id = target_instance_id
