# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .mssql_instance_summary import MssqlInstanceSummary


class MssqlInstanceDetail(MssqlInstanceSummary):
    """MssqlInstanceDetail.

    :param log_backup_frequency_in_seconds: Seconds between two log backups. A
     value of 0 disables log backup.
    :type log_backup_frequency_in_seconds: int
    :param log_retention_hours: Number of hours to retain a log backup. When
     the value is set to -1 the Rubrik cluster retains the log backup until the
     database snapshots that precede the log backup have expired.
    :type log_retention_hours: int
    :param copy_only: Set to true for copy-only backups of the database. Set
     to false for full or differential backups of the database.
    :type copy_only: bool
    :param id:
    :type id: str
    :param internal_timestamp:
    :type internal_timestamp: long
    :param name:
    :type name: str
    :param primary_cluster_id:
    :type primary_cluster_id: str
    :param root_properties:
    :type root_properties: :class:`MssqlRootProperties
     <rubriklib.models.MssqlRootProperties>`
    :param cluster_instance_address: The address of the instance in a Windows
     server failover cluster, populated only if it belongs to one.
    :type cluster_instance_address: str
    :param protection_date:
    :type protection_date: date
    :param version:
    :type version: str
    :param configured_sla_domain_id: SLA Domain ID assigned to instance
    :type configured_sla_domain_id: str
    :param configured_sla_domain_name: SLA Domain name assigned to instance
    :type configured_sla_domain_name: str
    """

    def __init__(self, log_backup_frequency_in_seconds=None, log_retention_hours=None, copy_only=None, id=None, internal_timestamp=None, name=None, primary_cluster_id=None, root_properties=None, cluster_instance_address=None, protection_date=None, version=None, configured_sla_domain_id=None, configured_sla_domain_name=None):
        super(MssqlInstanceDetail, self).__init__(log_backup_frequency_in_seconds=log_backup_frequency_in_seconds, log_retention_hours=log_retention_hours, copy_only=copy_only, id=id, internal_timestamp=internal_timestamp, name=name, primary_cluster_id=primary_cluster_id, root_properties=root_properties, cluster_instance_address=cluster_instance_address, protection_date=protection_date, version=version, configured_sla_domain_id=configured_sla_domain_id, configured_sla_domain_name=configured_sla_domain_name)
