# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SessionSummary(Model):
    """SessionSummary.

    :param id:
    :type id: str
    :param user_id:
    :type user_id: str
    :param token:
    :type token: str
    """

    _validation = {
        'id': {'required': True},
        'user_id': {'required': True},
        'token': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'user_id': {'key': 'userId', 'type': 'str'},
        'token': {'key': 'token', 'type': 'str'},
    }

    def __init__(self, id, user_id, token):
        self.id = id
        self.user_id = user_id
        self.token = token
