# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VcenterPatch(Model):
    """VcenterPatch.

    :param ca_certs: Concatenated X.509 certificates in Base64 encoded DER
     format. Each certificate must start with -----BEGIN CERTIFICATE----- and
     end with -----END CERTIFICATE-----. Use an empty string to remove the
     existing certificates for the vCenter.
    :type ca_certs: str
    :param configured_sla_domain_id: ID of the SLA Domain that is configured
     for this vCenter Server.
    :type configured_sla_domain_id: str
    """

    _attribute_map = {
        'ca_certs': {'key': 'caCerts', 'type': 'str'},
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
    }

    def __init__(self, ca_certs=None, configured_sla_domain_id=None):
        self.ca_certs = ca_certs
        self.configured_sla_domain_id = configured_sla_domain_id
