# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VmwareHostDetail(Model):
    """VmwareHostDetail.

    :param configured_sla_domain_id: ID of the SLA Domain that is configured
     for this ESXi hypervisor.
    :type configured_sla_domain_id: str
    :param datacenter_id:
    :type datacenter_id: str
    :param compute_cluster_id:
    :type compute_cluster_id: str
    :param datastores:
    :type datastores: list of :class:`DataStoreSummary
     <rubriklib.models.DataStoreSummary>`
    :param moid:
    :type moid: str
    :param datacenter:
    :type datacenter: :class:`DataCenterSummary
     <rubriklib.models.DataCenterSummary>`
    :param virtual_machines:
    :type virtual_machines: list of :class:`VirtualMachineSummary
     <rubriklib.models.VirtualMachineSummary>`
    """

    _attribute_map = {
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
        'datacenter_id': {'key': 'datacenterId', 'type': 'str'},
        'compute_cluster_id': {'key': 'computeClusterId', 'type': 'str'},
        'datastores': {'key': 'datastores', 'type': '[DataStoreSummary]'},
        'moid': {'key': 'moid', 'type': 'str'},
        'datacenter': {'key': 'datacenter', 'type': 'DataCenterSummary'},
        'virtual_machines': {'key': 'virtualMachines', 'type': '[VirtualMachineSummary]'},
    }

    def __init__(self, configured_sla_domain_id=None, datacenter_id=None, compute_cluster_id=None, datastores=None, moid=None, datacenter=None, virtual_machines=None):
        self.configured_sla_domain_id = configured_sla_domain_id
        self.datacenter_id = datacenter_id
        self.compute_cluster_id = compute_cluster_id
        self.datastores = datastores
        self.moid = moid
        self.datacenter = datacenter
        self.virtual_machines = virtual_machines
