# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WindowsClusterSummary(Model):
    """WindowsClusterSummary.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param fqdn: Fully qualified domain name of this cluster.
    :type fqdn: str
    :param host_ids: IDs of the hosts in this cluster.
    :type host_ids: list of str
    :param primary_cluster_id:
    :type primary_cluster_id: str
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'fqdn': {'required': True},
        'host_ids': {'required': True},
        'primary_cluster_id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'fqdn': {'key': 'fqdn', 'type': 'str'},
        'host_ids': {'key': 'hostIds', 'type': '[str]'},
        'primary_cluster_id': {'key': 'primaryClusterId', 'type': 'str'},
    }

    def __init__(self, id, name, fqdn, host_ids, primary_cluster_id):
        self.id = id
        self.name = name
        self.fqdn = fqdn
        self.host_ids = host_ids
        self.primary_cluster_id = primary_cluster_id
