# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .rubrik_lib import RubrikLib
from .version import VERSION

__all__ = ['RubrikLib']

__version__ = VERSION

