# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClusterVersion(Model):
    """ClusterVersion.

    :param version: Rubrik cluster software version
    :type version: str
    """

    _validation = {
        'version': {'required': True},
    }

    _attribute_map = {
        'version': {'key': 'version', 'type': 'str'},
    }

    def __init__(self, version):
        self.version = version
