# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HostRegister(Model):
    """HostRegister.

    :param hostname:
    :type hostname: str
    :param has_agent:
    :type has_agent: bool
    """

    _validation = {
        'hostname': {'required': True},
    }

    _attribute_map = {
        'hostname': {'key': 'hostname', 'type': 'str'},
        'has_agent': {'key': 'hasAgent', 'type': 'bool'},
    }

    def __init__(self, hostname, has_agent=None):
        self.hostname = hostname
        self.has_agent = has_agent
