# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MissedSnapshot(Model):
    """MissedSnapshot.

    :param archival_location_type:
    :type archival_location_type: list of str
    :param missed_snapshot_time:
    :type missed_snapshot_time: datetime
    """

    _validation = {
        'archival_location_type': {'required': True},
        'missed_snapshot_time': {'required': True},
    }

    _attribute_map = {
        'archival_location_type': {'key': 'archivalLocationType', 'type': '[str]'},
        'missed_snapshot_time': {'key': 'missedSnapshotTime', 'type': 'iso-8601'},
    }

    def __init__(self, archival_location_type, missed_snapshot_time):
        self.archival_location_type = archival_location_type
        self.missed_snapshot_time = missed_snapshot_time
