# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MssqlMissedRecoverableRange(Model):
    """MssqlMissedRecoverableRange.

    :param begin_time:
    :type begin_time: datetime
    :param end_time:
    :type end_time: datetime
    :param error_type:
    :type error_type: str
    :param description:
    :type description: str
    :param first_error:
    :type first_error: :class:`MssqlMissedRecoverableRangeError
     <rubriklib.models.MssqlMissedRecoverableRangeError>`
    :param last_error:
    :type last_error: :class:`MssqlMissedRecoverableRangeError
     <rubriklib.models.MssqlMissedRecoverableRangeError>`
    """

    _validation = {
        'begin_time': {'required': True},
        'end_time': {'required': True},
        'error_type': {'required': True},
        'description': {'required': True},
    }

    _attribute_map = {
        'begin_time': {'key': 'beginTime', 'type': 'iso-8601'},
        'end_time': {'key': 'endTime', 'type': 'iso-8601'},
        'error_type': {'key': 'errorType', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'first_error': {'key': 'firstError', 'type': 'MssqlMissedRecoverableRangeError'},
        'last_error': {'key': 'lastError', 'type': 'MssqlMissedRecoverableRangeError'},
    }

    def __init__(self, begin_time, end_time, error_type, description, first_error=None, last_error=None):
        self.begin_time = begin_time
        self.end_time = end_time
        self.error_type = error_type
        self.description = description
        self.first_error = first_error
        self.last_error = last_error
