# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .base_on_demand_snapshot_config import BaseOnDemandSnapshotConfig


class MssqlBackupJobConfig(BaseOnDemandSnapshotConfig):
    """MssqlBackupJobConfig.

    :param sla_id:
    :type sla_id: str
    :param force_full_snapshot: Whether to force a full snapshot or an
     incremental.
    :type force_full_snapshot: bool
    """

    _attribute_map = {
        'sla_id': {'key': 'slaId', 'type': 'str'},
        'force_full_snapshot': {'key': 'forceFullSnapshot', 'type': 'bool'},
    }

    def __init__(self, sla_id=None, force_full_snapshot=None):
        super(MssqlBackupJobConfig, self).__init__(sla_id=sla_id)
        self.force_full_snapshot = force_full_snapshot
