# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .mssql_non_sla_properties import MssqlNonSlaProperties


class MssqlInstanceUpdate(MssqlNonSlaProperties):
    """MssqlInstanceUpdate.

    :param log_backup_frequency_in_seconds: Seconds between two log backups. A
     value of 0 disables log backup.
    :type log_backup_frequency_in_seconds: int
    :param log_retention_hours: Number of hours to retain a log backup. When
     the value is set to -1 the Rubrik cluster retains the log backup until the
     database snapshots that precede the log backup have expired.
    :type log_retention_hours: int
    :param copy_only: Set to true for copy-only backups of the database. Set
     to false for full or differential backups of the database.
    :type copy_only: bool
    :param cluster_instance_address: Address of the instance in a Windows
     server failover cluster.
    :type cluster_instance_address: str
    :param configured_sla_domain_id: ID of the SLA Domain assigned to the
     instance
    :type configured_sla_domain_id: str
    """

    _attribute_map = {
        'log_backup_frequency_in_seconds': {'key': 'logBackupFrequencyInSeconds', 'type': 'int'},
        'log_retention_hours': {'key': 'logRetentionHours', 'type': 'int'},
        'copy_only': {'key': 'copyOnly', 'type': 'bool'},
        'cluster_instance_address': {'key': 'clusterInstanceAddress', 'type': 'str'},
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
    }

    def __init__(self, log_backup_frequency_in_seconds=None, log_retention_hours=None, copy_only=None, cluster_instance_address=None, configured_sla_domain_id=None):
        super(MssqlInstanceUpdate, self).__init__(log_backup_frequency_in_seconds=log_backup_frequency_in_seconds, log_retention_hours=log_retention_hours, copy_only=copy_only)
        self.cluster_instance_address = cluster_instance_address
        self.configured_sla_domain_id = configured_sla_domain_id
