# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .windows_cluster_summary import WindowsClusterSummary


class WindowsClusterDetail(WindowsClusterSummary):
    """WindowsClusterDetail.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param fqdn: Fully qualified domain name of this cluster.
    :type fqdn: str
    :param host_ids: IDs of the hosts in this cluster.
    :type host_ids: list of str
    :param primary_cluster_id:
    :type primary_cluster_id: str
    :param natural_id: Obtained from ClusterInstanceID under the registry key
     HKLM\\Cluster.
    :type natural_id: str
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'fqdn': {'required': True},
        'host_ids': {'required': True},
        'primary_cluster_id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'fqdn': {'key': 'fqdn', 'type': 'str'},
        'host_ids': {'key': 'hostIds', 'type': '[str]'},
        'primary_cluster_id': {'key': 'primaryClusterId', 'type': 'str'},
        'natural_id': {'key': 'naturalId', 'type': 'str'},
    }

    def __init__(self, id, name, fqdn, host_ids, primary_cluster_id, natural_id=None):
        super(WindowsClusterDetail, self).__init__(id=id, name=name, fqdn=fqdn, host_ids=host_ids, primary_cluster_id=primary_cluster_id)
        self.natural_id = natural_id
