# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AddNodesStatus(Model):
    """AddNodesStatus.

    :param status:
    :type status: str
    :param message:
    :type message: str
    :param ip_config:
    :type ip_config: str
    :param cassandra_setup:
    :type cassandra_setup: str
    :param start_services:
    :type start_services: str
    :param ipmi_config:
    :type ipmi_config: str
    :param setup_disks:
    :type setup_disks: str
    :param setup_encryption_at_rest:
    :type setup_encryption_at_rest: str
    :param setup_root_disks:
    :type setup_root_disks: str
    :param create_top_level_filesystem_dirs:
    :type create_top_level_filesystem_dirs: str
    :param setup_loop_devices:
    :type setup_loop_devices: str
    """

    _validation = {
        'status': {'required': True},
        'message': {'required': True},
        'ip_config': {'required': True},
        'cassandra_setup': {'required': True},
        'start_services': {'required': True},
        'ipmi_config': {'required': True},
        'setup_disks': {'required': True},
        'setup_encryption_at_rest': {'required': True},
        'setup_root_disks': {'required': True},
        'create_top_level_filesystem_dirs': {'required': True},
        'setup_loop_devices': {'required': True},
    }

    _attribute_map = {
        'status': {'key': 'status', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'ip_config': {'key': 'ipConfig', 'type': 'str'},
        'cassandra_setup': {'key': 'cassandraSetup', 'type': 'str'},
        'start_services': {'key': 'startServices', 'type': 'str'},
        'ipmi_config': {'key': 'ipmiConfig', 'type': 'str'},
        'setup_disks': {'key': 'setupDisks', 'type': 'str'},
        'setup_encryption_at_rest': {'key': 'setupEncryptionAtRest', 'type': 'str'},
        'setup_root_disks': {'key': 'setupRootDisks', 'type': 'str'},
        'create_top_level_filesystem_dirs': {'key': 'createTopLevelFilesystemDirs', 'type': 'str'},
        'setup_loop_devices': {'key': 'setupLoopDevices', 'type': 'str'},
    }

    def __init__(self, status, message, ip_config, cassandra_setup, start_services, ipmi_config, setup_disks, setup_encryption_at_rest, setup_root_disks, create_top_level_filesystem_dirs, setup_loop_devices):
        self.status = status
        self.message = message
        self.ip_config = ip_config
        self.cassandra_setup = cassandra_setup
        self.start_services = start_services
        self.ipmi_config = ipmi_config
        self.setup_disks = setup_disks
        self.setup_encryption_at_rest = setup_encryption_at_rest
        self.setup_root_disks = setup_root_disks
        self.create_top_level_filesystem_dirs = create_top_level_filesystem_dirs
        self.setup_loop_devices = setup_loop_devices
