# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AwsImageDetail(Model):
    """AwsImageDetail.

    :param aws_security_group_ids: For AWS instances, this is the security
     group ID. For images, this is the default security group ID for new
     instances from this image.
    :type aws_security_group_ids: list of str
    :param instance_ids: All instances that have been instantiated from this
     image
    :type instance_ids: list of str
    :param links:
    :type links: :class:`CloudImageDetailLinks
     <rubriklib_int.models.CloudImageDetailLinks>`
    """

    _attribute_map = {
        'aws_security_group_ids': {'key': 'awsSecurityGroupIds', 'type': '[str]'},
        'instance_ids': {'key': 'instanceIds', 'type': '[str]'},
        'links': {'key': 'links', 'type': 'CloudImageDetailLinks'},
    }

    def __init__(self, aws_security_group_ids=None, instance_ids=None, links=None):
        self.aws_security_group_ids = aws_security_group_ids
        self.instance_ids = instance_ids
        self.links = links
