# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BackupWindow(Model):
    """BackupWindow.

    :param start_time_attributes:
    :type start_time_attributes: :class:`SlaStartTimeAttributes
     <rubriklib_int.models.SlaStartTimeAttributes>`
    :param duration_in_hours:
    :type duration_in_hours: int
    """

    _validation = {
        'start_time_attributes': {'required': True},
        'duration_in_hours': {'required': True},
    }

    _attribute_map = {
        'start_time_attributes': {'key': 'startTimeAttributes', 'type': 'SlaStartTimeAttributes'},
        'duration_in_hours': {'key': 'durationInHours', 'type': 'int'},
    }

    def __init__(self, start_time_attributes, duration_in_hours):
        self.start_time_attributes = start_time_attributes
        self.duration_in_hours = duration_in_hours
