# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BackupJobConfig(Model):
    """BackupJobConfig.

    :param vm_id: ID of the VM to back up
    :type vm_id: str
    :param preferred_replicas:
    :type preferred_replicas: list of str
    :param is_on_demand_snapshot: Indicates if snapshot is on-demand
    :type is_on_demand_snapshot: bool
    :param config:
    :type config: :class:`BaseOnDemandSnapshotConfig
     <rubriklib_int.models.BaseOnDemandSnapshotConfig>`
    """

    _validation = {
        'vm_id': {'required': True},
    }

    _attribute_map = {
        'vm_id': {'key': 'vmId', 'type': 'str'},
        'preferred_replicas': {'key': 'preferredReplicas', 'type': '[str]'},
        'is_on_demand_snapshot': {'key': 'isOnDemandSnapshot', 'type': 'bool'},
        'config': {'key': 'config', 'type': 'BaseOnDemandSnapshotConfig'},
    }

    def __init__(self, vm_id, preferred_replicas=None, is_on_demand_snapshot=None, config=None):
        self.vm_id = vm_id
        self.preferred_replicas = preferred_replicas
        self.is_on_demand_snapshot = is_on_demand_snapshot
        self.config = config
