# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BaseGuestCredential(Model):
    """BaseGuestCredential.

    :param username: Username for the account used to login to the VM guest
     OS. To include a domain, use the format <domain>\\<username>.
    :type username: str
    :param password: Password for the account used to login to the VM guest
     OS.
    :type password: str
    """

    _validation = {
        'username': {'required': True},
        'password': {'required': True},
    }

    _attribute_map = {
        'username': {'key': 'username', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
    }

    def __init__(self, username, password):
        self.username = username
        self.password = password
