# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BaseOnDemandSnapshotConfig(Model):
    """BaseOnDemandSnapshotConfig.

    :param sla_id:
    :type sla_id: str
    """

    _attribute_map = {
        'sla_id': {'key': 'slaId', 'type': 'str'},
    }

    def __init__(self, sla_id=None):
        self.sla_id = sla_id
