# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CreateCloudInstanceRequest(Model):
    """CreateCloudInstanceRequest.

    :param snappable_id: The snappable id to which the snapshot belongs to
    :type snappable_id: str
    :param snapshot_id: The snapshot to create an instance from
    :type snapshot_id: str
    :param instantiate_location_id: The data location to instantiate on
    :type instantiate_location_id: str
    :param instance_type: Type of the launched instance
    :type instance_type: str
    :param security_group: A security group that the instance will be launched
     with
    :type security_group: str
    :param subnet: A subnet in which the instance will be launched
    :type subnet: str
    """

    _validation = {
        'snappable_id': {'required': True},
        'snapshot_id': {'required': True},
        'instantiate_location_id': {'required': True},
        'instance_type': {'required': True},
        'security_group': {'required': True},
        'subnet': {'required': True},
    }

    _attribute_map = {
        'snappable_id': {'key': 'snappableId', 'type': 'str'},
        'snapshot_id': {'key': 'snapshotId', 'type': 'str'},
        'instantiate_location_id': {'key': 'instantiateLocationId', 'type': 'str'},
        'instance_type': {'key': 'instanceType', 'type': 'str'},
        'security_group': {'key': 'securityGroup', 'type': 'str'},
        'subnet': {'key': 'subnet', 'type': 'str'},
    }

    def __init__(self, snappable_id, snapshot_id, instantiate_location_id, instance_type, security_group, subnet):
        self.snappable_id = snappable_id
        self.snapshot_id = snapshot_id
        self.instantiate_location_id = instantiate_location_id
        self.instance_type = instance_type
        self.security_group = security_group
        self.subnet = subnet
