# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeleteReplicationSourceJob(Model):
    """DeleteReplicationSourceJob.

    :param job_id:
    :type job_id: str
    :param location_id:
    :type location_id: str
    """

    _validation = {
        'job_id': {'required': True},
        'location_id': {'required': True},
    }

    _attribute_map = {
        'job_id': {'key': 'jobId', 'type': 'str'},
        'location_id': {'key': 'locationId', 'type': 'str'},
    }

    def __init__(self, job_id, location_id):
        self.job_id = job_id
        self.location_id = location_id
