# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .capacity import Capacity


class DiskCapacity(Capacity):
    """DiskCapacity.

    :param bytes:
    :type bytes: long
    :param is_encrypted:
    :type is_encrypted: bool
    """

    _validation = {
        'bytes': {'required': True},
    }

    _attribute_map = {
        'bytes': {'key': 'bytes', 'type': 'long'},
        'is_encrypted': {'key': 'isEncrypted', 'type': 'bool'},
    }

    def __init__(self, bytes, is_encrypted=None):
        super(DiskCapacity, self).__init__(bytes=bytes)
        self.is_encrypted = is_encrypted
