# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EmailSubscriptionCreate(Model):
    """EmailSubscriptionCreate.

    :param time_attributes:
    :type time_attributes: :class:`ScheduleTimeAttributes
     <rubriklib_int.models.ScheduleTimeAttributes>`
    :param email_addresses: Email addresses to send reports to.
    :type email_addresses: list of str
    """

    _validation = {
        'time_attributes': {'required': True},
        'email_addresses': {'required': True},
    }

    _attribute_map = {
        'time_attributes': {'key': 'timeAttributes', 'type': 'ScheduleTimeAttributes'},
        'email_addresses': {'key': 'emailAddresses', 'type': '[str]'},
    }

    def __init__(self, time_attributes, email_addresses):
        self.time_attributes = time_attributes
        self.email_addresses = email_addresses
