# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .email_subscription_create import EmailSubscriptionCreate


class EmailSubscriptionSummary(EmailSubscriptionCreate):
    """EmailSubscriptionSummary.

    :param time_attributes:
    :type time_attributes: :class:`ScheduleTimeAttributes
     <rubriklib_int.models.ScheduleTimeAttributes>`
    :param email_addresses: Email addresses to send reports to.
    :type email_addresses: list of str
    :param id:
    :type id: str
    """

    _validation = {
        'time_attributes': {'required': True},
        'email_addresses': {'required': True},
    }

    _attribute_map = {
        'time_attributes': {'key': 'timeAttributes', 'type': 'ScheduleTimeAttributes'},
        'email_addresses': {'key': 'emailAddresses', 'type': '[str]'},
        'id': {'key': 'id', 'type': 'str'},
    }

    def __init__(self, time_attributes, email_addresses, id=None):
        super(EmailSubscriptionSummary, self).__init__(time_attributes=time_attributes, email_addresses=email_addresses)
        self.id = id
