# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EventSummary(Model):
    """EventSummary.

    :param id:
    :type id: str
    :param object_id:
    :type object_id: str
    :param object_type:
    :type object_type: str
    :param object_name:
    :type object_name: str
    :param event_info:
    :type event_info: str
    :param time:
    :type time: str
    :param event_type:
    :type event_type: str
    :param event_status:
    :type event_status: str
    :param event_series_id:
    :type event_series_id: str
    :param event_progress:
    :type event_progress: str
    :param is_cancelable:
    :type is_cancelable: bool
    :param is_cancel_requested:
    :type is_cancel_requested: bool
    """

    _validation = {
        'id': {'required': True},
        'object_id': {'required': True},
        'object_type': {'required': True},
        'event_info': {'required': True},
        'time': {'required': True},
        'event_type': {'required': True},
        'event_status': {'required': True},
        'event_series_id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'object_id': {'key': 'objectId', 'type': 'str'},
        'object_type': {'key': 'objectType', 'type': 'str'},
        'object_name': {'key': 'objectName', 'type': 'str'},
        'event_info': {'key': 'eventInfo', 'type': 'str'},
        'time': {'key': 'time', 'type': 'str'},
        'event_type': {'key': 'eventType', 'type': 'str'},
        'event_status': {'key': 'eventStatus', 'type': 'str'},
        'event_series_id': {'key': 'eventSeriesId', 'type': 'str'},
        'event_progress': {'key': 'eventProgress', 'type': 'str'},
        'is_cancelable': {'key': 'isCancelable', 'type': 'bool'},
        'is_cancel_requested': {'key': 'isCancelRequested', 'type': 'bool'},
    }

    def __init__(self, id, object_id, object_type, event_info, time, event_type, event_status, event_series_id, object_name=None, event_progress=None, is_cancelable=None, is_cancel_requested=None):
        self.id = id
        self.object_id = object_id
        self.object_type = object_type
        self.object_name = object_name
        self.event_info = event_info
        self.time = time
        self.event_type = event_type
        self.event_status = event_status
        self.event_series_id = event_series_id
        self.event_progress = event_progress
        self.is_cancelable = is_cancelable
        self.is_cancel_requested = is_cancel_requested
