# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GenerateSupportBundleRequest(Model):
    """GenerateSupportBundleRequest.

    :param event_id:
    :type event_id: str
    :param request_ids:
    :type request_ids: list of str
    """

    _attribute_map = {
        'event_id': {'key': 'eventId', 'type': 'str'},
        'request_ids': {'key': 'requestIds', 'type': '[str]'},
    }

    def __init__(self, event_id=None, request_ids=None):
        self.event_id = event_id
        self.request_ids = request_ids
