# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GlobalAtlasConfig(Model):
    """GlobalAtlasConfig.

    :param default_snapshot_encoding_type: Default snapshot encoding type
    :type default_snapshot_encoding_type: int
    :param default_snapshot_replication_factor: Default snapshot replication
     factor
    :type default_snapshot_replication_factor: int
    :param default_journal_replication_factor: Default journal replication
     factor
    :type default_journal_replication_factor: int
    :param compacted_patch_dir_replication_factor: Compacted patch file
     replication factor for merged files
    :type compacted_patch_dir_replication_factor: int
    :param default_journal_media_type: Media type to use for journal files (1
     = FLASH, 2 = HDD)
    :type default_journal_media_type: int
    :param default_scratch_media_type: Media type to use for scratch files (1
     = FLASH, 2 = HDD)
    :type default_scratch_media_type: int
    :param brik_failure_tolerance: Number of brik failures to tolerate
    :type brik_failure_tolerance: int
    :param metadata_scan_enabled: Is metadata scan enabled
    :type metadata_scan_enabled: bool
    :param maintenance_manager_nthreads: Number of threads to use for running
     maintenance manager operations
    :type maintenance_manager_nthreads: int
    :param maintenance_manager_weights: Weights for each queue for the
     maintenance manager
    :type maintenance_manager_weights: str
    :param drain_node_failure_tolerance: Number of OK node failures that each
     stripe with chunks on a node in PRE_MAINTENANCE needs to be able to
     tolerate.
    :type drain_node_failure_tolerance: int
    :param store_events_in_cockroach_db: Store Events in CockroachDb
    :type store_events_in_cockroach_db: bool
    """

    _attribute_map = {
        'default_snapshot_encoding_type': {'key': 'default_snapshot_encoding_type', 'type': 'int'},
        'default_snapshot_replication_factor': {'key': 'default_snapshot_replication_factor', 'type': 'int'},
        'default_journal_replication_factor': {'key': 'default_journal_replication_factor', 'type': 'int'},
        'compacted_patch_dir_replication_factor': {'key': 'compacted_patch_dir_replication_factor', 'type': 'int'},
        'default_journal_media_type': {'key': 'default_journal_media_type', 'type': 'int'},
        'default_scratch_media_type': {'key': 'default_scratch_media_type', 'type': 'int'},
        'brik_failure_tolerance': {'key': 'brik_failure_tolerance', 'type': 'int'},
        'metadata_scan_enabled': {'key': 'metadata_scan_enabled', 'type': 'bool'},
        'maintenance_manager_nthreads': {'key': 'maintenance_manager_nthreads', 'type': 'int'},
        'maintenance_manager_weights': {'key': 'maintenance_manager_weights', 'type': 'str'},
        'drain_node_failure_tolerance': {'key': 'drain_node_failure_tolerance', 'type': 'int'},
        'store_events_in_cockroach_db': {'key': 'storeEventsInCockroachDb', 'type': 'bool'},
    }

    def __init__(self, default_snapshot_encoding_type=None, default_snapshot_replication_factor=None, default_journal_replication_factor=None, compacted_patch_dir_replication_factor=None, default_journal_media_type=None, default_scratch_media_type=None, brik_failure_tolerance=None, metadata_scan_enabled=None, maintenance_manager_nthreads=None, maintenance_manager_weights=None, drain_node_failure_tolerance=None, store_events_in_cockroach_db=None):
        self.default_snapshot_encoding_type = default_snapshot_encoding_type
        self.default_snapshot_replication_factor = default_snapshot_replication_factor
        self.default_journal_replication_factor = default_journal_replication_factor
        self.compacted_patch_dir_replication_factor = compacted_patch_dir_replication_factor
        self.default_journal_media_type = default_journal_media_type
        self.default_scratch_media_type = default_scratch_media_type
        self.brik_failure_tolerance = brik_failure_tolerance
        self.metadata_scan_enabled = metadata_scan_enabled
        self.maintenance_manager_nthreads = maintenance_manager_nthreads
        self.maintenance_manager_weights = maintenance_manager_weights
        self.drain_node_failure_tolerance = drain_node_failure_tolerance
        self.store_events_in_cockroach_db = store_events_in_cockroach_db
