# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GlobalCrystalConfig(Model):
    """GlobalCrystalConfig.

    :param use_autoprotect_sla_assignment_workflow: Whether to use older bulk
     assignment workflow or newer autoprotect workflow in the VM Assignment
     Screen
    :type use_autoprotect_sla_assignment_workflow: bool
    :param use_new_vm_assignment_screen: Whether to use the new VM assignment
     screen
    :type use_new_vm_assignment_screen: bool
    :param use_new_vm_details: Whether to use the new VM Details screen
    :type use_new_vm_details: bool
    :param enable_single_node_mode: Whether to display UI associated with
     single node appliance
    :type enable_single_node_mode: bool
    :param enable_data_network_configuration: Whether to display UI associated
     with dedicated data network
    :type enable_data_network_configuration: bool
    :param enable_ipmi_configuration: Whether to display UI associated with
     IPMI
    :type enable_ipmi_configuration: bool
    :param use_remote_replication_retention_panel: Whether to show UI
     associstaed with remote replication retention
    :type use_remote_replication_retention_panel: bool
    :param use_local_replication_retention_panel: Whether to show UI
     associstaed with local replication retention
    :type use_local_replication_retention_panel: bool
    :param enable_throttling_ui: Whether to display UI associated with
     throttling
    :type enable_throttling_ui: bool
    :param api_token_time_to_live_minutes: Number of minutes a REST API token
     can be idle before expiration
    :type api_token_time_to_live_minutes: int
    :param api_tokens_per_user: Number of active REST API tokens a user can
     have
    :type api_tokens_per_user: int
    :param missed_snapshot_activity_interval: Number of hours to look before
     and after a missed snapshot for activities
    :type missed_snapshot_activity_interval: int
    :param enable_missed_snapshots_page: Associates the missing snapshot times
     with their activity details
    :type enable_missed_snapshots_page: bool
    :param unmanaged_object_pagination_limit: Pagination limit for the
     unmanaged object page
    :type unmanaged_object_pagination_limit: int
    :param enable_organizations: Whether to display UI associated with
     Organizations
    :type enable_organizations: bool
    :param global_search_load_delay_in_sec: How long to delay loading global
     search
    :type global_search_load_delay_in_sec: int
    :param enable_convert_to_cloud: Whether to display UI for convert-to-cloud
     feature
    :type enable_convert_to_cloud: bool
    :param enable_kmip_and_key_rotation: Whether to enable KMIP setting and
     key rotation
    :type enable_kmip_and_key_rotation: bool
    """

    _attribute_map = {
        'use_autoprotect_sla_assignment_workflow': {'key': 'useAutoprotectSlaAssignmentWorkflow', 'type': 'bool'},
        'use_new_vm_assignment_screen': {'key': 'useNewVmAssignmentScreen', 'type': 'bool'},
        'use_new_vm_details': {'key': 'useNewVmDetails', 'type': 'bool'},
        'enable_single_node_mode': {'key': 'enableSingleNodeMode', 'type': 'bool'},
        'enable_data_network_configuration': {'key': 'enableDataNetworkConfiguration', 'type': 'bool'},
        'enable_ipmi_configuration': {'key': 'enableIpmiConfiguration', 'type': 'bool'},
        'use_remote_replication_retention_panel': {'key': 'useRemoteReplicationRetentionPanel', 'type': 'bool'},
        'use_local_replication_retention_panel': {'key': 'useLocalReplicationRetentionPanel', 'type': 'bool'},
        'enable_throttling_ui': {'key': 'enableThrottlingUi', 'type': 'bool'},
        'api_token_time_to_live_minutes': {'key': 'apiTokenTimeToLiveMinutes', 'type': 'int'},
        'api_tokens_per_user': {'key': 'apiTokensPerUser', 'type': 'int'},
        'missed_snapshot_activity_interval': {'key': 'missedSnapshotActivityInterval', 'type': 'int'},
        'enable_missed_snapshots_page': {'key': 'enableMissedSnapshotsPage', 'type': 'bool'},
        'unmanaged_object_pagination_limit': {'key': 'unmanagedObjectPaginationLimit', 'type': 'int'},
        'enable_organizations': {'key': 'enableOrganizations', 'type': 'bool'},
        'global_search_load_delay_in_sec': {'key': 'globalSearchLoadDelayInSec', 'type': 'int'},
        'enable_convert_to_cloud': {'key': 'enableConvertToCloud', 'type': 'bool'},
        'enable_kmip_and_key_rotation': {'key': 'enableKmipAndKeyRotation', 'type': 'bool'},
    }

    def __init__(self, use_autoprotect_sla_assignment_workflow=None, use_new_vm_assignment_screen=None, use_new_vm_details=None, enable_single_node_mode=None, enable_data_network_configuration=None, enable_ipmi_configuration=None, use_remote_replication_retention_panel=None, use_local_replication_retention_panel=None, enable_throttling_ui=None, api_token_time_to_live_minutes=None, api_tokens_per_user=None, missed_snapshot_activity_interval=None, enable_missed_snapshots_page=None, unmanaged_object_pagination_limit=None, enable_organizations=None, global_search_load_delay_in_sec=None, enable_convert_to_cloud=None, enable_kmip_and_key_rotation=None):
        self.use_autoprotect_sla_assignment_workflow = use_autoprotect_sla_assignment_workflow
        self.use_new_vm_assignment_screen = use_new_vm_assignment_screen
        self.use_new_vm_details = use_new_vm_details
        self.enable_single_node_mode = enable_single_node_mode
        self.enable_data_network_configuration = enable_data_network_configuration
        self.enable_ipmi_configuration = enable_ipmi_configuration
        self.use_remote_replication_retention_panel = use_remote_replication_retention_panel
        self.use_local_replication_retention_panel = use_local_replication_retention_panel
        self.enable_throttling_ui = enable_throttling_ui
        self.api_token_time_to_live_minutes = api_token_time_to_live_minutes
        self.api_tokens_per_user = api_tokens_per_user
        self.missed_snapshot_activity_interval = missed_snapshot_activity_interval
        self.enable_missed_snapshots_page = enable_missed_snapshots_page
        self.unmanaged_object_pagination_limit = unmanaged_object_pagination_limit
        self.enable_organizations = enable_organizations
        self.global_search_load_delay_in_sec = global_search_load_delay_in_sec
        self.enable_convert_to_cloud = enable_convert_to_cloud
        self.enable_kmip_and_key_rotation = enable_kmip_and_key_rotation
