# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HostFilesetDetail(Model):
    """HostFilesetDetail.

    :param id:
    :type id: str
    :param hostname:
    :type hostname: str
    :param primary_cluster_id:
    :type primary_cluster_id: str
    :param agent_id:
    :type agent_id: str
    :param operating_system:
    :type operating_system: str
    :param operating_system_type:
    :type operating_system_type: str
    :param status:
    :type status: str
    :param filesets:
    :type filesets: list of :class:`FilesetDetail
     <rubriklib_int.models.FilesetDetail>`
    """

    _validation = {
        'id': {'required': True},
        'hostname': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'hostname': {'key': 'hostname', 'type': 'str'},
        'primary_cluster_id': {'key': 'primaryClusterId', 'type': 'str'},
        'agent_id': {'key': 'agentId', 'type': 'str'},
        'operating_system': {'key': 'operatingSystem', 'type': 'str'},
        'operating_system_type': {'key': 'operatingSystemType', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'filesets': {'key': 'filesets', 'type': '[FilesetDetail]'},
    }

    def __init__(self, id, hostname, primary_cluster_id=None, agent_id=None, operating_system=None, operating_system_type=None, status=None, filesets=None):
        self.id = id
        self.hostname = hostname
        self.primary_cluster_id = primary_cluster_id
        self.agent_id = agent_id
        self.operating_system = operating_system
        self.operating_system_type = operating_system_type
        self.status = status
        self.filesets = filesets
