# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HypervVirtualMachineDetail(Model):
    """HypervVirtualMachineDetail.

    :param configured_sla_domain_id: Assign this VM to the given SLA domain.
    :type configured_sla_domain_id: str
    :param root_id: The name of the Hyper-V host or cluster
    :type root_id: str
    :param root_name: Name of the root of this object.
    :type root_name: str
    :param is_relic:
    :type is_relic: bool
    :param infra_path: Brief info of all the objects in the infrastructure
     path to this VM
    :type infra_path: list of :class:`ManagedHierarchyObjectAncestor
     <rubriklib_int.models.ManagedHierarchyObjectAncestor>`
    :param operating_system_type: Possible values include: 'Linux', 'Windows'
    :type operating_system_type: str or :class:`enum
     <rubriklib_int.models.enum>`
    :param is_agent_registered: Returns whether the Rubrik connector is
     installed and service is registered.
    :type is_agent_registered: bool
    """

    _attribute_map = {
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
        'root_id': {'key': 'rootId', 'type': 'str'},
        'root_name': {'key': 'rootName', 'type': 'str'},
        'is_relic': {'key': 'isRelic', 'type': 'bool'},
        'infra_path': {'key': 'infraPath', 'type': '[ManagedHierarchyObjectAncestor]'},
        'operating_system_type': {'key': 'operatingSystemType', 'type': 'str'},
        'is_agent_registered': {'key': 'isAgentRegistered', 'type': 'bool'},
    }

    def __init__(self, configured_sla_domain_id=None, root_id=None, root_name=None, is_relic=None, infra_path=None, operating_system_type=None, is_agent_registered=None):
        self.configured_sla_domain_id = configured_sla_domain_id
        self.root_id = root_id
        self.root_name = root_name
        self.is_relic = is_relic
        self.infra_path = infra_path
        self.operating_system_type = operating_system_type
        self.is_agent_registered = is_agent_registered
