# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .hyperv_virtual_machine_mount_summary import HypervVirtualMachineMountSummary


class HypervVirtualMachineMountDetail(HypervVirtualMachineMountSummary):
    """HypervVirtualMachineMountDetail.

    :param id:
    :type id: str
    :param snapshot_date:
    :type snapshot_date: datetime
    :param vm_id:
    :type vm_id: str
    :param vm_name:
    :type vm_name: str
    :param mounted_vm_id:
    :type mounted_vm_id: str
    :param mounted_vm_name:
    :type mounted_vm_name: str
    :param host_id:
    :type host_id: str
    :param host_name:
    :type host_name: str
    :param is_ready:
    :type is_ready: bool
    :param power_status: The power status of the mounted VM(ON,OFF,SLEEP
     etc.). Possible values include: 'PoweringOn', 'PoweredOn', 'PoweringOff',
     'PoweredOff'
    :type power_status: str or :class:`enum <rubriklib_int.models.enum>`
    :param mount_request_id:
    :type mount_request_id: str
    :param unmount_request_id:
    :type unmount_request_id: str
    """

    _validation = {
        'id': {'required': True},
        'snapshot_date': {'required': True},
        'vm_id': {'required': True},
        'vm_name': {'required': True},
        'is_ready': {'required': True},
        'power_status': {'required': True},
    }

    def __init__(self, id, snapshot_date, vm_id, vm_name, is_ready, power_status, mounted_vm_id=None, mounted_vm_name=None, host_id=None, host_name=None, mount_request_id=None, unmount_request_id=None):
        super(HypervVirtualMachineMountDetail, self).__init__(id=id, snapshot_date=snapshot_date, vm_id=vm_id, vm_name=vm_name, mounted_vm_id=mounted_vm_id, mounted_vm_name=mounted_vm_name, host_id=host_id, host_name=host_name, is_ready=is_ready, power_status=power_status, mount_request_id=mount_request_id, unmount_request_id=unmount_request_id)
