# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HypervRestoreFileConfig(Model):
    """HypervRestoreFileConfig.

    :param path: Absolute file path
    :type path: str
    :param restore_path: Directory of folder to copy files into
    :type restore_path: str
    """

    _validation = {
        'path': {'required': True},
        'restore_path': {'required': True},
    }

    _attribute_map = {
        'path': {'key': 'path', 'type': 'str'},
        'restore_path': {'key': 'restorePath', 'type': 'str'},
    }

    def __init__(self, path, restore_path):
        self.path = path
        self.restore_path = restore_path
