# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HypervExportSnapshotJobConfig(Model):
    """HypervExportSnapshotJobConfig.

    :param vm_name: name of the new VM for export
    :type vm_name: str
    :param host_id: ID of the host to export to
    :type host_id: str
    :param path: Destination path for the new VM virtual disks
    :type path: str
    :param disable_network: Whether the network should be disabled on
     mount.This should be set true to avoid ip conflict in case of static IPs
    :type disable_network: bool
    :param power_on: Whether the VM should be powered on after export. Default
     value is true
    :type power_on: bool
    """

    _validation = {
        'path': {'required': True},
    }

    _attribute_map = {
        'vm_name': {'key': 'vmName', 'type': 'str'},
        'host_id': {'key': 'hostId', 'type': 'str'},
        'path': {'key': 'path', 'type': 'str'},
        'disable_network': {'key': 'disableNetwork', 'type': 'bool'},
        'power_on': {'key': 'powerOn', 'type': 'bool'},
    }

    def __init__(self, path, vm_name=None, host_id=None, disable_network=None, power_on=None):
        self.vm_name = vm_name
        self.host_id = host_id
        self.path = path
        self.disable_network = disable_network
        self.power_on = power_on
