# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class InternalExpireSnapshotConfig(Model):
    """InternalExpireSnapshotConfig.

    :param snapshot_id: ID of the snapshot to expire
    :type snapshot_id: str
    :param location_id: ID of the location to expire in, or empty if all
    :type location_id: str
    """

    _validation = {
        'snapshot_id': {'required': True},
    }

    _attribute_map = {
        'snapshot_id': {'key': 'snapshotId', 'type': 'str'},
        'location_id': {'key': 'locationId', 'type': 'str'},
    }

    def __init__(self, snapshot_id, location_id=None):
        self.snapshot_id = snapshot_id
        self.location_id = location_id
