# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IpConfig(Model):
    """IpConfig.

    :param address:
    :type address: str
    :param netmask:
    :type netmask: str
    :param gateway:
    :type gateway: str
    :param vlan:
    :type vlan: int
    """

    _validation = {
        'address': {'required': True},
        'netmask': {'required': True},
        'gateway': {'required': True},
    }

    _attribute_map = {
        'address': {'key': 'address', 'type': 'str'},
        'netmask': {'key': 'netmask', 'type': 'str'},
        'gateway': {'key': 'gateway', 'type': 'str'},
        'vlan': {'key': 'vlan', 'type': 'int'},
    }

    def __init__(self, address, netmask, gateway, vlan=None):
        self.address = address
        self.netmask = netmask
        self.gateway = gateway
        self.vlan = vlan
