# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LocationPathPoint(Model):
    """LocationPathPoint.

    :param managed_id:
    :type managed_id: str
    :param name:
    :type name: str
    """

    _validation = {
        'managed_id': {'required': True},
        'name': {'required': True},
    }

    _attribute_map = {
        'managed_id': {'key': 'managedId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, managed_id, name):
        self.managed_id = managed_id
        self.name = name
