# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ManagedVolumeExport(Model):
    """ManagedVolumeExport.

    :param is_active: Is export active.
    :type is_active: bool
    :param channels: Channels of this export.
    :type channels: list of :class:`ManagedVolumeChannelConfig
     <rubriklib_int.models.ManagedVolumeChannelConfig>`
    :param config:
    :type config: :class:`ManagedVolumeExportConfig
     <rubriklib_int.models.ManagedVolumeExportConfig>`
    """

    _validation = {
        'is_active': {'required': True},
        'channels': {'required': True},
        'config': {'required': True},
    }

    _attribute_map = {
        'is_active': {'key': 'isActive', 'type': 'bool'},
        'channels': {'key': 'channels', 'type': '[ManagedVolumeChannelConfig]'},
        'config': {'key': 'config', 'type': 'ManagedVolumeExportConfig'},
    }

    def __init__(self, is_active, channels, config):
        self.is_active = is_active
        self.channels = channels
        self.config = config
