# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .bulk_status import BulkStatus


class MssqlDbSlaAssignStatus(BulkStatus):
    """MssqlDbSlaAssignStatus.

    :param statuses:
    :type statuses: list of :class:`IdStatus <rubriklib_int.models.IdStatus>`
    :param unprotected_databases: IDs of databases unprotected in order to
     protect the corresponding database. Since only one database in an
     availability group may be protected at a time, protecting databases may
     involve unprotecting other databases. Note that databases will only be
     unprotected if the force parameter in the SLA assignment request was set
     to true.
    :type unprotected_databases: list of str
    """

    _validation = {
        'statuses': {'required': True},
    }

    _attribute_map = {
        'statuses': {'key': 'statuses', 'type': '[IdStatus]'},
        'unprotected_databases': {'key': 'unprotectedDatabases', 'type': '[str]'},
    }

    def __init__(self, statuses, unprotected_databases=None):
        super(MssqlDbSlaAssignStatus, self).__init__(statuses=statuses)
        self.unprotected_databases = unprotected_databases
