# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MssqlRestoreFile(Model):
    """MssqlRestoreFile.

    :param logical_name: Logical name of the database file to be restored.
    :type logical_name: str
    :param original_path: Original path of the database file to be restored.
    :type original_path: str
    :param original_name: Original filename of the database file to be
     restored.
    :type original_name: str
    :param length: Length of the file in bytes.
    :type length: long
    :param is_log: Whether this file is the transaction log file.
    :type is_log: bool
    :param file_id: Original file ID of the database file to be restored.
    :type file_id: long
    """

    _validation = {
        'logical_name': {'required': True},
        'original_path': {'required': True},
        'original_name': {'required': True},
        'length': {'required': True},
        'is_log': {'required': True},
        'file_id': {'required': True},
    }

    _attribute_map = {
        'logical_name': {'key': 'logicalName', 'type': 'str'},
        'original_path': {'key': 'originalPath', 'type': 'str'},
        'original_name': {'key': 'originalName', 'type': 'str'},
        'length': {'key': 'length', 'type': 'long'},
        'is_log': {'key': 'isLog', 'type': 'bool'},
        'file_id': {'key': 'fileId', 'type': 'long'},
    }

    def __init__(self, logical_name, original_path, original_name, length, is_log, file_id):
        self.logical_name = logical_name
        self.original_path = original_path
        self.original_name = original_name
        self.length = length
        self.is_log = is_log
        self.file_id = file_id
