# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MssqlDbUpdateId(Model):
    """MssqlDbUpdateId.

    :param database_id: ID of the Microsoft SQL database.
    :type database_id: str
    :param update_properties:
    :type update_properties: :class:`MssqlDbUpdate
     <rubriklib_int.models.MssqlDbUpdate>`
    """

    _validation = {
        'database_id': {'required': True},
        'update_properties': {'required': True},
    }

    _attribute_map = {
        'database_id': {'key': 'databaseId', 'type': 'str'},
        'update_properties': {'key': 'updateProperties', 'type': 'MssqlDbUpdate'},
    }

    def __init__(self, database_id, update_properties):
        self.database_id = database_id
        self.update_properties = update_properties
