# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .mssql_availability_group_summary import MssqlAvailabilityGroupSummary


class MssqlAvailabilityGroupDetail(MssqlAvailabilityGroupSummary):
    """MssqlAvailabilityGroupDetail.

    :param sla_assignment: SLA assignment type. Possible values include:
     'Derived', 'Direct', 'Unassigned'
    :type sla_assignment: str or :class:`enum <rubriklib_int.models.enum>`
    :param effective_sla_domain_id: ID of the effective SLA domain
    :type effective_sla_domain_id: str
    :param effective_sla_domain_name: name of the effective SLA domain
    :type effective_sla_domain_name: str
    :param effective_sla_source_object_id: ID of the object from which the
     effective SLA domain is inherited
    :type effective_sla_source_object_id: str
    :param effective_sla_source_object_name: Name of the object from which the
     effective SLA domain is inherited
    :type effective_sla_source_object_name: str
    :param log_backup_frequency_in_seconds: Seconds between two log backups. A
     value of 0 disables log backup.
    :type log_backup_frequency_in_seconds: int
    :param log_retention_hours: Number of hours to retain a log backup. When
     the value is set to -1 the Rubrik cluster retains the log backup until the
     database snapshots that precede the log backup have expired.
    :type log_retention_hours: int
    :param copy_only: Set to true for copy-only backups of the database. Set
     to false for full or differential backups of the database.
    :type copy_only: bool
    """

    def __init__(self, sla_assignment=None, effective_sla_domain_id=None, effective_sla_domain_name=None, effective_sla_source_object_id=None, effective_sla_source_object_name=None, log_backup_frequency_in_seconds=None, log_retention_hours=None, copy_only=None):
        super(MssqlAvailabilityGroupDetail, self).__init__(sla_assignment=sla_assignment, effective_sla_domain_id=effective_sla_domain_id, effective_sla_domain_name=effective_sla_domain_name, effective_sla_source_object_id=effective_sla_source_object_id, effective_sla_source_object_name=effective_sla_source_object_name, log_backup_frequency_in_seconds=log_backup_frequency_in_seconds, log_retention_hours=log_retention_hours, copy_only=copy_only)
