# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NfsLocationDetail(Model):
    """NfsLocationDetail.

    :param id:
    :type id: str
    :param definition:
    :type definition: :class:`NfsLocationDefinition
     <rubriklib_int.models.NfsLocationDefinition>`
    """

    _validation = {
        'id': {'required': True},
        'definition': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'definition': {'key': 'definition', 'type': 'NfsLocationDefinition'},
    }

    def __init__(self, id, definition):
        self.id = id
        self.definition = definition
