# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NutanixClusterConfig(Model):
    """NutanixClusterConfig.

    :param hostname: Address for the Prism host. Any Prism Element or Prism
     central host will do. We will use the highly available IP, if set, and
     this address, if not, to communicate with the cluster.
    :type hostname: str
    :param nutanix_cluster_uuid: The UUID of the Nutanix cluster being added.
     This is required because Prism Central may manage multiple clusters, and
     we need to differentiate between them.
    :type nutanix_cluster_uuid: str
    :param username:
    :type username: str
    :param password:
    :type password: str
    :param ca_certs: Concatenated X.509 certificates in Base64 encoded DER
     format. Each certificate must start with -----BEGIN CERTIFICATE----- and
     end with -----END CERTIFICATE-----.
    :type ca_certs: str
    """

    _validation = {
        'hostname': {'required': True},
        'nutanix_cluster_uuid': {'required': True},
        'username': {'required': True},
        'password': {'required': True},
        'ca_certs': {'required': True},
    }

    _attribute_map = {
        'hostname': {'key': 'hostname', 'type': 'str'},
        'nutanix_cluster_uuid': {'key': 'nutanixClusterUuid', 'type': 'str'},
        'username': {'key': 'username', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'ca_certs': {'key': 'caCerts', 'type': 'str'},
    }

    def __init__(self, hostname, nutanix_cluster_uuid, username, password, ca_certs):
        self.hostname = hostname
        self.nutanix_cluster_uuid = nutanix_cluster_uuid
        self.username = username
        self.password = password
        self.ca_certs = ca_certs
