# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NutanixClusterPatch(Model):
    """NutanixClusterPatch.

    :param hostname: Address for the Prism host. Any Prism Element or Prism
     central host will do. We will use the highly available IP, if set, and
     this address, if not, to communicate with the cluster.
    :type hostname: str
    :param username:
    :type username: str
    :param password:
    :type password: str
    :param ca_certs: Concatenated X.509 certificates in Base64 encoded DER
     format. Each certificate must start with -----BEGIN CERTIFICATE----- and
     end with -----END CERTIFICATE-----.
    :type ca_certs: str
    :param configured_sla_domain_id: ID of the SLA Domain that is configured
     for this Nutanix Cluster.
    :type configured_sla_domain_id: str
    """

    _attribute_map = {
        'hostname': {'key': 'hostname', 'type': 'str'},
        'username': {'key': 'username', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'ca_certs': {'key': 'caCerts', 'type': 'str'},
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
    }

    def __init__(self, hostname=None, username=None, password=None, ca_certs=None, configured_sla_domain_id=None):
        self.hostname = hostname
        self.username = username
        self.password = password
        self.ca_certs = ca_certs
        self.configured_sla_domain_id = configured_sla_domain_id
