# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .managed_hierarchy_object_summary import ManagedHierarchyObjectSummary


class NutanixHierarchyObjectSummary(ManagedHierarchyObjectSummary):
    """NutanixHierarchyObjectSummary.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param configured_sla_domain_id: ID of the configured SLA domain
    :type configured_sla_domain_id: str
    :param configured_sla_domain_name: name of the configured SLA domain
    :type configured_sla_domain_name: str
    :param primary_cluster_id:
    :type primary_cluster_id: str
    :param sla_assignment: SLA assignment type. Possible values include:
     'Derived', 'Direct', 'Unassigned'
    :type sla_assignment: str or :class:`enum <rubriklib_int.models.enum>`
    :param effective_sla_domain_id: ID of the effective SLA domain
    :type effective_sla_domain_id: str
    :param effective_sla_domain_name: name of the effective SLA domain
    :type effective_sla_domain_name: str
    :param effective_sla_source_object_id: ID of the object from which the
     effective SLA domain is inherited
    :type effective_sla_source_object_id: str
    :param effective_sla_source_object_name: Name of the object from which the
     effective SLA domain is inherited
    :type effective_sla_source_object_name: str
    :param infra_path:
    :type infra_path: list of :class:`ManagedHierarchyObjectAncestor
     <rubriklib_int.models.ManagedHierarchyObjectAncestor>`
    :param sla_path:
    :type sla_path: list of :class:`ManagedHierarchyObjectAncestor
     <rubriklib_int.models.ManagedHierarchyObjectAncestor>`
    :param is_relic: Whether this managed object is a relic (an archived
     snappable with unexpired snapshots).
    :type is_relic: bool
    :param object_type: Type of object. Possible values include: 'cluster',
     'vm'
    :type object_type: str or :class:`enum <rubriklib_int.models.enum>`
    :param descendant_count:
    :type descendant_count: :class:`NutanixHierarchyObjectDescendantCount
     <rubriklib_int.models.NutanixHierarchyObjectDescendantCount>`
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'configured_sla_domain_id': {'required': True},
        'configured_sla_domain_name': {'required': True},
        'primary_cluster_id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'configured_sla_domain_id': {'key': 'configuredSlaDomainId', 'type': 'str'},
        'configured_sla_domain_name': {'key': 'configuredSlaDomainName', 'type': 'str'},
        'primary_cluster_id': {'key': 'primaryClusterId', 'type': 'str'},
        'sla_assignment': {'key': 'slaAssignment', 'type': 'str'},
        'effective_sla_domain_id': {'key': 'effectiveSlaDomainId', 'type': 'str'},
        'effective_sla_domain_name': {'key': 'effectiveSlaDomainName', 'type': 'str'},
        'effective_sla_source_object_id': {'key': 'effectiveSlaSourceObjectId', 'type': 'str'},
        'effective_sla_source_object_name': {'key': 'effectiveSlaSourceObjectName', 'type': 'str'},
        'infra_path': {'key': 'infraPath', 'type': '[ManagedHierarchyObjectAncestor]'},
        'sla_path': {'key': 'slaPath', 'type': '[ManagedHierarchyObjectAncestor]'},
        'is_relic': {'key': 'isRelic', 'type': 'bool'},
        'object_type': {'key': 'objectType', 'type': 'str'},
        'descendant_count': {'key': 'descendantCount', 'type': 'NutanixHierarchyObjectDescendantCount'},
    }

    def __init__(self, id, name, configured_sla_domain_id, configured_sla_domain_name, primary_cluster_id, sla_assignment=None, effective_sla_domain_id=None, effective_sla_domain_name=None, effective_sla_source_object_id=None, effective_sla_source_object_name=None, infra_path=None, sla_path=None, is_relic=None, object_type=None, descendant_count=None):
        super(NutanixHierarchyObjectSummary, self).__init__(id=id, name=name, configured_sla_domain_id=configured_sla_domain_id, configured_sla_domain_name=configured_sla_domain_name, primary_cluster_id=primary_cluster_id, sla_assignment=sla_assignment, effective_sla_domain_id=effective_sla_domain_id, effective_sla_domain_name=effective_sla_domain_name, effective_sla_source_object_id=effective_sla_source_object_id, effective_sla_source_object_name=effective_sla_source_object_name, infra_path=infra_path, sla_path=sla_path, is_relic=is_relic)
        self.object_type = object_type
        self.descendant_count = descendant_count
