# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NutanixVmExportSnapshotJobConfig(Model):
    """NutanixVmExportSnapshotJobConfig.

    :param container_natural_id: The natural ID of the container that will
     store the export VM's disks.
    :type container_natural_id: str
    :param nutanix_cluster_id: The ID of the Nutanix cluster to export to. If
     not specified, we will default to the VM's cluster.
    :type nutanix_cluster_id: str
    :param vm_name: name of the new VM for export
    :type vm_name: str
    :param power_on: Whether the VM should be powered on after export. Default
     value is true
    :type power_on: bool
    """

    _validation = {
        'container_natural_id': {'required': True},
    }

    _attribute_map = {
        'container_natural_id': {'key': 'containerNaturalId', 'type': 'str'},
        'nutanix_cluster_id': {'key': 'nutanixClusterId', 'type': 'str'},
        'vm_name': {'key': 'vmName', 'type': 'str'},
        'power_on': {'key': 'powerOn', 'type': 'bool'},
    }

    def __init__(self, container_natural_id, nutanix_cluster_id=None, vm_name=None, power_on=None):
        self.container_natural_id = container_natural_id
        self.nutanix_cluster_id = nutanix_cluster_id
        self.vm_name = vm_name
        self.power_on = power_on
