# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ObjectStoreLocationSummary(Model):
    """ObjectStoreLocationSummary.

    :param object_store_type:
    :type object_store_type: str
    :param name:
    :type name: str
    :param access_key:
    :type access_key: str
    :param bucket: Bucket name cannot contain whitespace or _\\\\/*?%.:|<> For
     AWS, bucket name also cannot contain capital letters or underscore
    :type bucket: str
    :param pem_file_content:
    :type pem_file_content: str
    :param kms_master_key_id:
    :type kms_master_key_id: str
    :param default_region:
    :type default_region: str
    :param endpoint:
    :type endpoint: str
    :param num_buckets:
    :type num_buckets: long
    :param is_compute_enabled:
    :type is_compute_enabled: bool
    :param compute_security_group_id:
    :type compute_security_group_id: str
    :param storage_class:
    :type storage_class: str
    """

    _validation = {
        'object_store_type': {'required': True},
        'name': {'required': True},
        'access_key': {'required': True},
        'bucket': {'required': True},
    }

    _attribute_map = {
        'object_store_type': {'key': 'objectStoreType', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'access_key': {'key': 'accessKey', 'type': 'str'},
        'bucket': {'key': 'bucket', 'type': 'str'},
        'pem_file_content': {'key': 'pemFileContent', 'type': 'str'},
        'kms_master_key_id': {'key': 'kmsMasterKeyId', 'type': 'str'},
        'default_region': {'key': 'defaultRegion', 'type': 'str'},
        'endpoint': {'key': 'endpoint', 'type': 'str'},
        'num_buckets': {'key': 'numBuckets', 'type': 'long'},
        'is_compute_enabled': {'key': 'isComputeEnabled', 'type': 'bool'},
        'compute_security_group_id': {'key': 'computeSecurityGroupId', 'type': 'str'},
        'storage_class': {'key': 'storageClass', 'type': 'str'},
    }

    def __init__(self, object_store_type, name, access_key, bucket, pem_file_content=None, kms_master_key_id=None, default_region=None, endpoint=None, num_buckets=None, is_compute_enabled=None, compute_security_group_id=None, storage_class=None):
        self.object_store_type = object_store_type
        self.name = name
        self.access_key = access_key
        self.bucket = bucket
        self.pem_file_content = pem_file_content
        self.kms_master_key_id = kms_master_key_id
        self.default_region = default_region
        self.endpoint = endpoint
        self.num_buckets = num_buckets
        self.is_compute_enabled = is_compute_enabled
        self.compute_security_group_id = compute_security_group_id
        self.storage_class = storage_class
