# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class OfflineStatSummary(Model):
    """OfflineStatSummary.

    :param name:
    :type name: str
    :param key:
    :type key: str
    :param value:
    :type value: str
    :param frequency_in_min:
    :type frequency_in_min: int
    :param last_update_time:
    :type last_update_time: datetime
    """

    _validation = {
        'name': {'required': True},
        'value': {'required': True},
        'frequency_in_min': {'required': True},
        'last_update_time': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'key': {'key': 'key', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
        'frequency_in_min': {'key': 'frequencyInMin', 'type': 'int'},
        'last_update_time': {'key': 'lastUpdateTime', 'type': 'iso-8601'},
    }

    def __init__(self, name, value, frequency_in_min, last_update_time, key=None):
        self.name = name
        self.key = key
        self.value = value
        self.frequency_in_min = frequency_in_min
        self.last_update_time = last_update_time
