# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class OrganizationDetail(Model):
    """OrganizationDetail.

    :param id: The unique id of the Orgnization
    :type id: str
    :param name: The name of the Organization
    :type name: str
    :param principal: The summary of all the principals in the Organization
    :type principal: list of :class:`OrganizationPrincipalSummary
     <rubriklib_int.models.OrganizationPrincipalSummary>`
    :param vmware: The ids of the VMware Hierarchy items in the Organization
    :type vmware: list of str
    :param hyperv: The ids of the Hyper-V Hierarchy items in the Organization
    :type hyperv: list of str
    :param windows: The ids of the Windows Fileset Hierarchy items in the
     Organization
    :type windows: list of str
    :param linux: The ids of the Linux Fileset Hierarchy items in the
     Organization
    :type linux: list of str
    :param managed_volume: The ids of the Managed Volume Hierarchy items in
     the Organization
    :type managed_volume: list of str
    :param nas_share: The ids of the NAS Share Hierarchy items in the
     Organization
    :type nas_share: list of str
    :param sql_server: The ids of the SQL Server Hierarchy items in the
     Organization
    :type sql_server: list of str
    :param sla_domain: The ids of the SLA Domains in the Organization
    :type sla_domain: list of str
    :param replication_target: The ids of the Replication Targets in the
     Organization
    :type replication_target: list of str
    :param archival_location: The ids of the Archival Locations in the
     Organization
    :type archival_location: list of str
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'principal': {'required': True},
        'vmware': {'required': True},
        'hyperv': {'required': True},
        'windows': {'required': True},
        'linux': {'required': True},
        'managed_volume': {'required': True},
        'nas_share': {'required': True},
        'sla_domain': {'required': True},
        'replication_target': {'required': True},
        'archival_location': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'principal': {'key': 'principal', 'type': '[OrganizationPrincipalSummary]'},
        'vmware': {'key': 'vmware', 'type': '[str]'},
        'hyperv': {'key': 'hyperv', 'type': '[str]'},
        'windows': {'key': 'windows', 'type': '[str]'},
        'linux': {'key': 'linux', 'type': '[str]'},
        'managed_volume': {'key': 'managed_volume', 'type': '[str]'},
        'nas_share': {'key': 'nas_share', 'type': '[str]'},
        'sql_server': {'key': 'sql_server', 'type': '[str]'},
        'sla_domain': {'key': 'sla_domain', 'type': '[str]'},
        'replication_target': {'key': 'replication_target', 'type': '[str]'},
        'archival_location': {'key': 'archival_location', 'type': '[str]'},
    }

    def __init__(self, id, name, principal, vmware, hyperv, windows, linux, managed_volume, nas_share, sla_domain, replication_target, archival_location, sql_server=None):
        self.id = id
        self.name = name
        self.principal = principal
        self.vmware = vmware
        self.hyperv = hyperv
        self.windows = windows
        self.linux = linux
        self.managed_volume = managed_volume
        self.nas_share = nas_share
        self.sql_server = sql_server
        self.sla_domain = sla_domain
        self.replication_target = replication_target
        self.archival_location = archival_location
