# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .organization_create import OrganizationCreate


class OrganizationUpdate(OrganizationCreate):
    """OrganizationUpdate.

    :param name: The name of the Organization
    :type name: str
    :param id: The id of the Organization to update
    :type id: str
    """

    _validation = {
        'name': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
    }

    def __init__(self, name, id=None):
        super(OrganizationUpdate, self).__init__(name=name)
        self.id = id
