# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Pkcs10CertificateSigningRequest(Model):
    """Pkcs10CertificateSigningRequest.

    :param csr: Base64 encoded PKCS#10 certificate signing request. The
     request should start with -----BEGIN CERTIFICATE REQUEST-----
    :type csr: str
    """

    _validation = {
        'csr': {'required': True},
    }

    _attribute_map = {
        'csr': {'key': 'csr', 'type': 'str'},
    }

    def __init__(self, csr):
        self.csr = csr
