# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RemoveNodeStatus(Model):
    """RemoveNodeStatus.

    :param status:
    :type status: str
    :param remove_cassandra:
    :type remove_cassandra: str
    """

    _validation = {
        'status': {'required': True},
        'remove_cassandra': {'required': True},
    }

    _attribute_map = {
        'status': {'key': 'status', 'type': 'str'},
        'remove_cassandra': {'key': 'removeCassandra', 'type': 'str'},
    }

    def __init__(self, status, remove_cassandra):
        self.status = status
        self.remove_cassandra = remove_cassandra
