# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReplicationStorage(Model):
    """ReplicationStorage.

    :param remote_vm_storage_on_premise:
    :type remote_vm_storage_on_premise: list of
     :class:`RemoteClusterStorageStats
     <rubriklib_int.models.RemoteClusterStorageStats>`
    :param local_vm_storage_across_all_targets:
    :type local_vm_storage_across_all_targets: list of
     :class:`RemoteClusterStorageStats
     <rubriklib_int.models.RemoteClusterStorageStats>`
    """

    _validation = {
        'remote_vm_storage_on_premise': {'required': True},
        'local_vm_storage_across_all_targets': {'required': True},
    }

    _attribute_map = {
        'remote_vm_storage_on_premise': {'key': 'remoteVmStorageOnPremise', 'type': '[RemoteClusterStorageStats]'},
        'local_vm_storage_across_all_targets': {'key': 'localVmStorageAcrossAllTargets', 'type': '[RemoteClusterStorageStats]'},
    }

    def __init__(self, remote_vm_storage_on_premise, local_vm_storage_across_all_targets):
        self.remote_vm_storage_on_premise = remote_vm_storage_on_premise
        self.local_vm_storage_across_all_targets = local_vm_storage_across_all_targets
