# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReportCreate(Model):
    """ReportCreate.

    :param name: The name of the report.
    :type name: str
    :param report_template: The template this report is based on. Possible
     values include: 'ProtectionTasksDetails', 'ProtectionTasksSummary',
     'SystemCapacity', 'SlaComplianceSummary'
    :type report_template: str or :class:`enum <rubriklib_int.models.enum>`
    """

    _validation = {
        'name': {'required': True},
        'report_template': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'report_template': {'key': 'reportTemplate', 'type': 'str'},
    }

    def __init__(self, name, report_template):
        self.name = name
        self.report_template = report_template
