# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SearchResponse(Model):
    """SearchResponse.

    :param path:
    :type path: str
    :param filename: Just the filename without the whole path
    :type filename: str
    :param file_versions:
    :type file_versions: list of :class:`FileVersion
     <rubriklib_int.models.FileVersion>`
    """

    _attribute_map = {
        'path': {'key': 'path', 'type': 'str'},
        'filename': {'key': 'filename', 'type': 'str'},
        'file_versions': {'key': 'fileVersions', 'type': '[FileVersion]'},
    }

    def __init__(self, path=None, filename=None, file_versions=None):
        self.path = path
        self.filename = filename
        self.file_versions = file_versions
