# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .syslog_server_settings_update import SyslogServerSettingsUpdate


class SyslogServerSettings(SyslogServerSettingsUpdate):
    """SyslogServerSettings.

    :param hostname:
    :type hostname: str
    :param port:
    :type port: int
    :param protocol: Network protocol. Possible values are: 'TCP' and 'UDP'
    :type protocol: str
    :param id:
    :type id: str
    """

    _attribute_map = {
        'hostname': {'key': 'hostname', 'type': 'str'},
        'port': {'key': 'port', 'type': 'int'},
        'protocol': {'key': 'protocol', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
    }

    def __init__(self, hostname=None, port=None, protocol=None, id=None):
        super(SyslogServerSettings, self).__init__(hostname=hostname, port=port, protocol=protocol)
        self.id = id
