# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TimeseriesRequest(Model):
    """TimeseriesRequest.

    :param id:
    :type id: str
    :param range:
    :type range: str
    """

    _validation = {
        'id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'range': {'key': 'range', 'type': 'str'},
    }

    def __init__(self, id, range=None):
        self.id = id
        self.range = range
