# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TimeStat(Model):
    """TimeStat.

    :param time:
    :type time: datetime
    :param stat:
    :type stat: long
    """

    _validation = {
        'time': {'required': True},
        'stat': {'required': True},
    }

    _attribute_map = {
        'time': {'key': 'time', 'type': 'iso-8601'},
        'stat': {'key': 'stat', 'type': 'long'},
    }

    def __init__(self, time, stat):
        self.time = time
        self.stat = stat
