# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UserDefinition(Model):
    """UserDefinition.

    :param id:
    :type id: str
    :param password:
    :type password: str
    :param first_name:
    :type first_name: str
    :param last_name:
    :type last_name: str
    :param email_address:
    :type email_address: str
    :param contact_number:
    :type contact_number: str
    """

    _validation = {
        'id': {'required': True},
        'password': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'first_name': {'key': 'firstName', 'type': 'str'},
        'last_name': {'key': 'lastName', 'type': 'str'},
        'email_address': {'key': 'emailAddress', 'type': 'str'},
        'contact_number': {'key': 'contactNumber', 'type': 'str'},
    }

    def __init__(self, id, password, first_name=None, last_name=None, email_address=None, contact_number=None):
        self.id = id
        self.password = password
        self.first_name = first_name
        self.last_name = last_name
        self.email_address = email_address
        self.contact_number = contact_number
