# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VirtualDiskDetail(Model):
    """VirtualDiskDetail.

    :param id:
    :type id: str
    :param file_name:
    :type file_name: str
    :param device_key: Unique and reusable key that vSphere uses to identify
     VMDK files and other devices in the hardware of a virtual machine.
    :type device_key: long
    :param size:
    :type size: long
    :param exclude_from_snapshots:
    :type exclude_from_snapshots: bool
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'file_name': {'key': 'fileName', 'type': 'str'},
        'device_key': {'key': 'deviceKey', 'type': 'long'},
        'size': {'key': 'size', 'type': 'long'},
        'exclude_from_snapshots': {'key': 'excludeFromSnapshots', 'type': 'bool'},
    }

    def __init__(self, id=None, file_name=None, device_key=None, size=None, exclude_from_snapshots=None):
        self.id = id
        self.file_name = file_name
        self.device_key = device_key
        self.size = size
        self.exclude_from_snapshots = exclude_from_snapshots
