# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VirtualDiskSummary(Model):
    """VirtualDiskSummary.

    :param id:
    :type id: str
    :param file_name:
    :type file_name: str
    :param vm_name:
    :type vm_name: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'file_name': {'key': 'fileName', 'type': 'str'},
        'vm_name': {'key': 'vmName', 'type': 'str'},
    }

    def __init__(self, id=None, file_name=None, vm_name=None):
        self.id = id
        self.file_name = file_name
        self.vm_name = vm_name
